### ISSUE TITLE
GZDoom Feature Request: Add Auto-Detection for GOG's Release of Heretic and Hexen 1

### ISSUE THREAD

**Issue by MasterO2** [coelckers/gzdoom#1254]
@coelckers @madame-rachelle 

Since Heretic and Hexen 1 are finally on [GOG](https://www.gog.com/game/heretic_hexen_collection), can auto-detection be added for those games?  

You may find this helpful as well:

https://www.doomworld.com/forum/topic/118748-heretic-hexen-1-and-hexen-2-are-now-on-gog/?tab=comments#comment-2233872

> Heretic: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\GOG.com\Games\1290366318
> Hexen: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\GOG.com\Games\1247951670
> Deathkings: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\GOG.com\Games\1983497091

**Comment by drfrag666** [comment]
If i understand this correctly i need to add (push) both the install folder and the MUSIC folder for the ogg music?

**Comment by Gaerzi** [comment]
Hexen is fine using its internal MUS soundtrack. The off music is the CD soundtrack, which is incomplete. See (https://doomwiki.org/wiki/Hexen_music)[Doom Wiki].

**Comment by drfrag666** [comment]
Now i think adding the music folder is not needed. I've made a PR: https://github.com/coelckers/gzdoom/pull/1259
