### ISSUE TITLE
Feature Request: Horizontally Moving and Rotating Sectors

### ISSUE THREAD

**Issue by UnizoneDev** [coelckers/gzdoom#1270]
This will take a while to implement, especially for any 2.5d platform that you can walk under and jump over, but think about it.

We could have moving crates held by cranes, easier to implement platforming sections, swinging locker doors, and even more dynamic explosion effects.

I imagine they would be defined somewhat like polyobjects, but with tags instead of angles.

And of course, we have to use special cylindrical collision handling for rotating sectors presumably defined in a IWADINFO or GAMEINFO lump, or at the very least in the options menu, because doom's collision code is fragmented and strange.

**Comment by MajorCooke** [comment]
Wasn't the Issues tab supposed to be disabled? That's what the Feature Suggestions form is for. https://forum.zdoom.org/viewforum.php?f=15&sid=72365d16b7e2eba7c655f17f3df71ca9

**Comment by UnizoneDev** [comment]
> 
> 
> Wasn't the Issues tab supposed to be disabled? That's what the Feature Suggestions form is for. https://forum.zdoom.org/viewforum.php?f=15&sid=72365d16b7e2eba7c655f17f3df71ca9

I was an Idiot who got Banned on the ZDoom Forums, so this is my other second Chance, besides Doomworld.

Also, I do apologize for that Idiotic Behavior on those Forums, I really do mean it!

**Comment by coelckers** [comment]
> 
> 
> Wasn't the Issues tab supposed to be disabled? That's what the Feature Suggestions form is for. https://forum.zdoom.org/viewforum.php?f=15&sid=72365d16b7e2eba7c655f17f3df71ca9

Actually, Rachael asked to reactivate it for some upcoming forum updates. But nothing has happened there yet.

Regarding the feature - rotating sectors are out as long as actors are squares. This just will not work properly. Moving sectors are theoretically possible but not easy to pull off with all those advanced mapping options present. It may be done in the future but don't hold your breath.
