### ISSUE TITLE
missing: ZMUSIC_LIBRARIES ZMUSIC_INCLUDE_DIR

### ISSUE THREAD

**Issue by Magicrafter13** [coelckers/gzdoom#1281]
Trying to build latest release on Manjaro (Arch), following the steps on the wiki, but I get this output:
```
CMake Error at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find ZMusic (missing: ZMUSIC_LIBRARIES ZMUSIC_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindZMusic.cmake:21 (find_package_handle_standard_args)
  src/CMakeLists.txt:20 (find_package)
```
There is nothing in the list of dependencies (on the wiki) that matches this, I can find almost 0 references to ZMUSIC online, and even searching the issues here turns up ZERO results!

**Comment by madame-rachelle** [comment]
[This library](https://github.com/coelckers/ZMusic) must be installed first.

**Comment by Magicrafter13** [comment]
Okay, well I figured out that ZMusic is one of your projects here on GitHub, so problem solved.

However, the Wiki should probably be updated to include it as a dependency.

**Comment by f1ames0ff** [comment]
@madame-rachelle How about add this to readme or in some place where people can find it?
