### ISSUE TITLE
GZDoom freezes on Linux Mint 20.1 Xfce after intro music ends

### ISSUE THREAD

**Issue by palaciodaniel** [coelckers/gzdoom#1283]
**Problem**
No error is raised, simply the buttons stop responding at all. The only thing that works is hovering the mouse, but clicking doesn't do anything. I have to force-quit GZDoom by opening a Terminal and using "xkill".

**Log**
I initialized GZDoom by using the Terminal, and I captured this error log.

fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.437: cannot register existing type 'IpatchSplitsType'
(gzdoom:12073): GLib-GObject-CRITICAL **: 04:34:57.437: g_param_spec_enum: assertion 'G_TYPE_IS_ENUM (enum_type)' failed
** (gzdoom:12073): CRITICAL **: 04:34:57.437: ipatch_type_install_property: assertion 'G_IS_PARAM_SPEC(prop_spec)' failed
(gzdoom:12073): GLib-GObject-CRITICAL **: 04:34:57.437: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.437: cannot register existing type 'IpatchSF2GenType'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.437: cannot retrieve class for invalid (unclassed) type '<invalid>'
** (gzdoom:12073): CRITICAL **: 04:34:57.437: file /build/libinstpatch-i701yY/libinstpatch-1.1.2/libinstpatch/IpatchSF2Gen.c: line 148 (_ipatch_sf2_gen_init): assertion `enum_class != NULL' failed.
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchSample'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchItem'
(gzdoom:12073): GLib-GObject-CRITICAL **: 04:34:57.438: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchSF2GenItem'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchItem'
(gzdoom:12073): GLib-GObject-CRITICAL **: 04:34:57.438: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchSF2ModItem'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchItem'
(gzdoom:12073): GLib-GObject-CRITICAL **: 04:34:57.438: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchSF2VoiceCache'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot retrieve class for invalid (unclassed) type '<invalid>'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchItem'
(gzdoom:12073): GLib-GObject-CRITICAL **: 04:34:57.438: g_type_register_static: assertion 'parent_type > 0' failed
(gzdoom:12073): GLib-GObject-CRITICAL **: 04:34:57.438: g_type_register_static: assertion 'parent_type > 0' failed
(gzdoom:12073): GLib-CRITICAL **: 04:34:57.438: g_once_init_leave: assertion 'result != 0' failed
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot retrieve class for invalid (unclassed) type '<invalid>'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchItem'
(gzdoom:12073): GLib-GObject-CRITICAL **: 04:34:57.438: g_type_register_static: assertion 'parent_type > 0' failed
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot retrieve class for invalid (unclassed) type '<invalid>'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot register existing type 'IpatchConverter'
(gzdoom:12073): GLib-GObject-WARNING **: 04:34:57.438: cannot retrieve class for invalid (unclassed) type '<invalid>'

**Solution**
This doesn't patch the underlying problem, but if you go to **Sound Options** and select *OPL Synth Emulation* on **Midi Device** before the intro song ends, everything starts working flawlessly.

**Comment by coelckers** [comment]
This is a known issue with a broken FluidSynth version shipped with some Linux distributions. I am sorry but this is something we cannot fix ourselves. The only way to get around this is to switch MIDI devices or update FluidSynth from an external source.
