### ISSUE TITLE
Make A_PosAttack and A_CyberAttack fullbright for zombieman and cyberdemon missile frames

### ISSUE THREAD

**Issue by maxmanium** [coelckers/gzdoom#1291]
This is fixed in the DEHACKED patch that comes with the Doom 2 minor sprite fixing project. I was surprised to see that they aren't in the internal definitions for these monsters. Unless there's a reason to the contrary that I'm unaware of.

**Comment by coelckers** [comment]
They are not in the internal definitions because originally they are not in the internal definitions. These definitions are the same as they were in Doom.exe.
