### ISSUE TITLE
[FEATURE REQUEST] Discord RPC

### ISSUE THREAD

**Issue by tedbysek** [coelckers/gzdoom#1295]
I really miss that my friends can't see what I am playing when I am playing gzdoom. I saw some rich presence clients before but none of them actually works, so I would like this feature built in. btw zandronum already has that.

**Comment by coelckers** [comment]
There will be no social media garbage being added to the engine. This topic is non-negotiable.

**Comment by tedbysek** [comment]
> There will be no social media garbage being added to the engine. This topic is non-negotiable.
> 

understandable, thanks for the engine.

**Comment by rollingmoai** [comment]
Implemented in https://github.com/ZDoom/gzdoom/releases/tag/g4.8.0, seems like things change 😅
