### ISSUE TITLE
(feature) Steamapi pk3 development, possibility, licensing?

### ISSUE THREAD

**Issue by arrowgent** [coelckers/gzdoom#1319]
**several steam games discussions using gzdoom as a base have asked for "steam achievements"**

so lets go to the source, and ask:  is this possible in gzdoom?

lets go through some issues...

- Seperate pk3 & build option to include
- Forking project to allow 3rd party steamapi integration
- Licensing the big one, how is steamapi distributable and codewise compatible with gzdoom

i know most "modders" and "game devs" just create wads using the tools for wad making
having code documented and a "def" to trigger steam achievements through the steamapi could be easy enough for them to manage inside the .wad/.pk3 files

for me, i know nothing of how steamapi.dll or .so (linux) handle the calls
i dont know how gzdoom can add some def for things like "you beat the game" or "you killed 1000 demons" etc

thoughts, considerations;
much appreciated and good luck if anyone can challenge the task

edit--
guess i need to search your other resources and read up on this
https://forum.zdoom.org/viewtopic.php?f=4&t=62882&hilit=steam+achievements

**Comment by coelckers** [comment]
I can only repeat what I said back then: By linking GZDoom to a proprietary library you are technically violating the GPL.
Keep in mind that there's a lot of code here that cannot be relicensed with a specific exception to allow this special case.

This means two things:
1. We cannot add code to the project that allows doing such a thing.
2. Even if you created a fork adding the SteamAPI to GZDoom, anybody who ever created code that is currently present in GZDoom and licensed under the GPL can have your project taken down due to licensing violations.

I'm sorry about that but that decision is final. Unless Steam releases a GPL friendly version of their API we'd enter shaky legal ground by supporting it.

**Comment by alexey-lysiuk** [comment]
It’s possible to create a fork of GZDoom that will use some kind of interprocess communication to notify external process(es) about anything you want. So, only a third-party executable will be linked with proprietary library.
Will this work with Steam API? If it allows to offload all operations with API to a child process, this will solve the problem.
However, you need to research this yourself, as it has nothing to do with GZDoom.

**Comment by coelckers** [comment]
But even then, to be legally in the clear, the protocol must be generic enough so it isn't tied to Steam and the child process is just processing some generic commands that can be directed to any kind of service. Otherwise the "mere aggregation" clause won't fly.

**Comment by arrowgent** [comment]
i did read the entire discussion, i see the points and faults.

thanks for your considerations

**Comment by madame-rachelle** [comment]
> 
> 
> It’s possible to create a fork of GZDoom that will use some kind of interprocess communication to notify external process(es) about anything you want. So, only a third-party executable will be linked with proprietary library.
> Will this work with Steam API? If it allows to offload all operations with API to a child process, this will solve the problem.
> However, you need to research this yourself, as it has nothing to do with GZDoom.

Yes, this will work. And it does allow you to skirt around the restrictions of the GPL as well. As long as said program (or library) is GPL-compliant (i.e. is open source at the very least) and is not actually licensed under the GPL. (The college licenses would work for this)

**Comment by coelckers** [comment]
A library is not "mere aggregation",
The trick here would be to write a generic interprocess interface API that is not game dependent and not Steam dependent, add support for it to GZDoom and then write a Steam implementation of it.
