### ISSUE TITLE
[Language bug] "jp" or "jap"

### ISSUE THREAD

**Issue by EkidonaArubino** [coelckers/gzdoom#1325]
I decided to create a translation of my project into my language ... I made an "ACSII font" and put it in my package with the game, but when I wrote the translation into "LANGUAGE", I met this: 
![anani](https://user-images.githubusercontent.com/76256186/109627176-665f7a00-7b52-11eb-9d42-75c215c87956.png)
Then I immediately got the idea that the problem might be in "jp", and I rewrote it in "jap" (like "eng" & "rus")... and it worked..! 
![afine](https://user-images.githubusercontent.com/76256186/109628308-a7a45980-7b53-11eb-842e-78ccac080925.png)
Everything would be fine, but...
![awf](https://user-images.githubusercontent.com/76256186/109628405-c30f6480-7b53-11eb-90ef-732badf4af56.PNG)
And again, this is written on https://zdoom.org/wiki/Internationalization: 
![aaaa](https://user-images.githubusercontent.com/76256186/109628616-023db580-7b54-11eb-9aaf-49f201651893.PNG)

**Comment by coelckers** [comment]
Japanese is "ja" not "jp", that page is wrong.

**Comment by Blue-Shadow** [comment]
> 
> 
> Japanese is "ja" not "jp", that page is wrong.

Looking at [MENUDEF](https://github.com/coelckers/gzdoom/blob/master/wadsrc/static/menudef.txt#L2783) and languge.csv, it's "jp", not "ja" (or "jap", even).

**Comment by EkidonaArubino** [comment]
Oufe... alright...

**Comment by EkidonaArubino** [comment]
> Japanese is "ja" not "jp", that page is wrong.

Something is wrong here: in MENUDEF - as in the LANGUAGE notation - there is "jp" (this is why the translation of the text appears in the settings) ...

**Comment by EkidonaArubino** [comment]
What's even stranger is that the Russian language - which I registered through "rus" - works ... 
![何１](https://user-images.githubusercontent.com/76256186/110212022-6e008500-7eaa-11eb-9bd5-47c2f5236639.PNG)
![何２](https://user-images.githubusercontent.com/76256186/110212023-6fca4880-7eaa-11eb-9259-4e2b464c8fc6.PNG)
![何３](https://user-images.githubusercontent.com/76256186/110212024-722ca280-7eaa-11eb-915b-ccd8498aa002.PNG)
Although it is also registered as "ru" in MENUDEF ...

**Comment by Cacodemon345** [comment]
It should be "ja" for Japanese, not "jp". GZDoom is wrong here.

**Comment by EkidonaArubino** [comment]
> It should be "ja" for Japanese, not "jp". GZDoom is wrong here.

Well, I explain in one piece and in order ... "jp" (menudef & language) is written in the engine code, but ACSII fonts do not understand it and give out the absence of my font, replacing it with consolfont (I have a standalone game in ipk3) .. . I decided to write "jap", and the font worked, but the translations in the settings were gone, which is logical (this is not a big loss, I can always write them in my language)... 
I also noticed an interesting thing with the names of languages: so, for example, I wrote "rus" instead of "ru", and the game understood this, so a Russian translation appeared in the settings ... the same thing with "jpn", which is similar to "jp "- having registered it, the font still did not work for me, but there was a translation in the settings ... 
It is for this reason that the spelling of "jap" will not differ from "ja", which I did ... I myself still cannot understand the problem, maybe it's all about the fonts ..? But ASCII works with "ja (p)", but not with "jp" ...

**Comment by Cacodemon345** [comment]
https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-LCID/%5bMS-LCID%5d.pdf

According to this doc "ja" stands for Japanese.
