### ISSUE TITLE
[Feature Request] MMPX texture scaling

### ISSUE THREAD

**Issue by DukeSkinny** [coelckers/gzdoom#1336]
The scaling algorithm MMPX as detailed [here](https://casual-effects.com/research/McGuire2021PixelArt/) seems to compare very favorably against xBRZ, both in terms of performance and overall quality of output.

While xBRZ is pretty darn good, there is still quite a bit of detail loss even at 2x.

**Comment by alexey-lysiuk** [comment]
I made a draft PR with MMPX upscaler, #1337. The problem is, I can barely notice a difference with and without it.
Pretty much everything was copied from the reference implementation.
If someone wants to check it out, grab `gzdoom.exe` and `gzdoom.pk3` from continuous integration build.

**Comment by DukeSkinny** [comment]
I just checked it out. In my estimation, it's working as intended. Compared to xBRZ there is significantly less blur/smudging, as well as overall less compromised structure in the texture work. Weapon sprites are barely affected it seems, same goes for a lot of wall textures.

Places to look for are the stage 1 grey floors, doors & the diagonal metal grills in the small room before the exit room itself. Basically everywhere diagonal lines feature heavily, the difference is not so subtle.

**Comment by coelckers** [comment]
The effect of this is virtually non-existent, I don't think this adds anything of value.
