### ISSUE TITLE
Visual Studio 19 (Newley Updated) Build Errors

### ISSUE THREAD

**Issue by UltronT800** [coelckers/gzdoom#1338]
![GZDoom 4 5 Compile Error](https://user-images.githubusercontent.com/18043666/110974393-19369180-8324-11eb-820a-08d9cb3dd572.png)

I attempted to compile GZDoom 4.5 with CMake & Visual Studio 19 and received the following errors.

**Comment by UltronT800** [comment]
I was able to compile LZDoom 3.87 successfully, I still received a few errors though. Posting another picture for the sake of documentation/consistency. 

![LZDoom 3 87 Compile Errors](https://user-images.githubusercontent.com/18043666/110976860-0e313080-8327-11eb-839f-06ece608e73a.png)

**Comment by alexey-lysiuk** [comment]
Cherry-pick 013078a02f9794df5f3ee6258a7ed60208e7a07b.
