### ISSUE TITLE
Vulkan HDR enabled on 4.5.0 -> dark and greyed out colors

### ISSUE THREAD

**Issue by mgtroyas** [coelckers/gzdoom#1350]
Using GZDoom 4.5.0 and and a LG 29WK600 HDR10 monitor.

I have the same problem that is described on this post:
https://forum.zdoom.org/viewtopic.php?f=290&t=70730#p1173971

If some testing is needed to tune HDR support on GZDoom I'm willing to help.

![GZDoom45-HDR](https://user-images.githubusercontent.com/30797135/111905762-a036e880-8a4d-11eb-8067-e64434382b67.png)

With HDR off on Windows desktop, image is the same:

![GZDoom45-noHDR](https://user-images.githubusercontent.com/30797135/111905849-0d4a7e00-8a4e-11eb-9c73-def65780f5ee.png)

**Comment by coelckers** [comment]
As the other report already exists, this will get closed as a duplicate.
The main problem here is that no developer has a HDR monitor to test with.
