### ISSUE TITLE
Problems with MIDI music in gzdoom 4.5.0. SIGSEGV or deadlock

### ISSUE THREAD

**Issue by milasudril** [coelckers/gzdoom#1357]
The latest release is broken on Ubuntu 20.04:

$ gdb --args gzdoom -file /home/delat/Doom-wads/LaTailorGirl_v1_77.pk3 

MAP01 - Entryway

fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchSplitsType'

(gzdoom:22472): GLib-GObject-CRITICAL **: 20:29:26.700: g_param_spec_enum: assertion 'G_TYPE_IS_ENUM (enum_type)' failed

** (gzdoom:22472): CRITICAL **: 20:29:26.700: ipatch_type_install_property: assertion 'G_IS_PARAM_SPEC(prop_spec)' failed

(gzdoom:22472): GLib-GObject-CRITICAL **: 20:29:26.700: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchSF2GenType'

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot retrieve class for invalid (unclassed) type '<invalid>'

** (gzdoom:22472): CRITICAL **: 20:29:26.700: file /build/libinstpatch-i701yY/libinstpatch-1.1.2/libinstpatch/IpatchSF2Gen.c: line 148 (_ipatch_sf2_gen_init): assertion `enum_class != NULL' failed.

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchSample'

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchItem'

(gzdoom:22472): GLib-GObject-CRITICAL **: 20:29:26.700: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchSF2GenItem'

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchItem'

(gzdoom:22472): GLib-GObject-CRITICAL **: 20:29:26.700: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchSF2ModItem'

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchItem'

(gzdoom:22472): GLib-GObject-CRITICAL **: 20:29:26.700: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot register existing type 'IpatchSF2VoiceCache'

(gzdoom:22472): GLib-GObject-WARNING **: 20:29:26.700: cannot retrieve class for invalid (unclassed) type '<invalid>'

Thread 1 "gzdoom" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff67168c0 (LWP 22472)]
__strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
101     ../sysdeps/x86_64/multiarch/strcmp-avx2.S: Filen eller katalogen finns inte.
(gdb) bt
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x00007ffff4f805dd in g_str_equal () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4f7f7cd in g_hash_table_lookup () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4fa2bcf in g_intern_static_string () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fffd82ffa1d in  () at /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
#5  0x00007fffd82ffdb5 in ipatch_base_get_type () at /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
#6  0x00007fffd835b557 in ipatch_init () at /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
#7  0x00007fffd900aed4 in new_fluid_synth () at /lib/x86_64-linux-gnu/libfluidsynth.so.2
#8  0x00007ffff7a13f7a in FluidSynthMIDIDevice::FluidSynthMIDIDevice(int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () at /usr/local/lib/libzmusic.so.1
#9  0x00007ffff7a1440e in CreateFluidSynthMIDIDevice(int, char const*) () at /usr/local/lib/libzmusic.so.1
#10 0x00007ffff7a21eef in MIDIStreamer::CreateMIDIDevice(EMidiDevice_, int) () at /usr/local/lib/libzmusic.so.1
#11 0x00007ffff7a22c00 in MIDIStreamer::Play(bool, int) () at /usr/local/lib/libzmusic.so.1
#12 0x00007ffff7a27aee in ZMusic_Start () at /usr/local/lib/libzmusic.so.1
#13 0x0000555556063fbc in S_StartMusicPlaying(ZMusic_MusicStream, bool, float, int)
    (song=0x55555e77e840, loop=true, rel_vol=1, subsong=0) at /dev/shm/gzdoom/src/common/audio/music/music.cpp:217
#14 0x0000555556065cce in S_ChangeMusic(char const*, int, bool, bool)
    (musicname=0x55555e2bb1bc "D_runnin", order=0, looping=true, force=false)
    at /dev/shm/gzdoom/src/common/audio/music/music.cpp:708
#15 0x0000555555d56803 in FLevelLocals::SetMusic() (this=0x555557085760 <level>)
    at /dev/shm/gzdoom/src/g_level.cpp:2279
#16 0x0000555555e4c5a1 in P_SetupLevel(FLevelLocals*, int, bool)
    (Level=0x555557085760 <level>, position=0, newGame=true) at /dev/shm/gzdoom/src/p_setup.cpp:441
#17 0x0000555555d51cfa in FLevelLocals::DoLoadLevel(FString const&, int, bool, bool)
    (this=0x555557085760 <level>, nextmapname=..., position=0, autosave=false, newGame=true)
    at /dev/shm/gzdoom/src/g_level.cpp:1185
#18 0x0000555555d518a0 in G_DoLoadLevel(FString const&, int, bool, bool)
    (nextmapname=..., position=0, autosave=false, newGame=true) at /dev/shm/gzdoom/src/g_level.cpp:1077
#19 0x0000555555d4fbd8 in G_InitNew(char const*, bool) (mapname=0x5555580e06dc "map01", bTitleLevel=false)
    at /dev/shm/gzdoom/src/g_level.cpp:555
#20 0x0000555555d4f6de in G_DoNewGame() () at /dev/shm/gzdoom/src/g_level.cpp:424
#21 0x0000555555d44339 in G_Ticker() () at /dev/shm/gzdoom/src/g_game.cpp:1149
#22 0x0000555555d337eb in TryRunTics() () at /dev/shm/gzdoom/src/d_net.cpp:1987
#23 0x0000555555d2389b in D_DoomLoop() () at /dev/shm/gzdoom/src/d_main.cpp:1288
#24 0x0000555555d29f2d in D_DoomMain_Internal() () at /dev/shm/gzdoom/src/d_main.cpp:3648
#25 0x0000555555d2a24e in GameMain() () at /dev/shm/gzdoom/src/d_main.cpp:3678
#26 0x00005555559e418b in main(int, char**) (argc=3, argv=0x7fffffffdfb8)
    at /dev/shm/gzdoom/src/common/platform/posix/sdl/i_main.cpp:194
(gdb) frame 9
#9  0x00007ffff7a1440e in CreateFluidSynthMIDIDevice(int, char const*) () from /usr/local/lib/libzmusic.so.1
(gdb) frame 26
#26 0x00005555559e418b in main (argc=3, argv=0x7fffffffdfb8)

Crash occurs when trying to enter MAP01 in Doom2.wad. It looks like it tries to compare strings. If I do not load any extra mod, there appears to be a deadlock:

#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4fdf623 in g_cond_wait () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4fbbcaf in g_once_init_enter () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffd8263dac in ipatch_base_get_type () at /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
#4  0x00007fffd826bc71 in ipatch_dls2_get_type () at /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
#5  0x00007fffd82bf57e in ipatch_init () at /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
#6  0x00007fffd8330ed4 in new_fluid_synth () at /lib/x86_64-linux-gnu/libfluidsynth.so.2
#7  0x00007ffff7a13f7a in FluidSynthMIDIDevice::FluidSynthMIDIDevice(int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () at /usr/local/lib/libzmusic.so.1
#8  0x00007ffff7a1440e in CreateFluidSynthMIDIDevice(int, char const*) () at /usr/local/lib/libzmusic.so.1
#9  0x00007ffff7a21eef in MIDIStreamer::CreateMIDIDevice(EMidiDevice_, int) () at /usr/local/lib/libzmusic.so.1
#10 0x00007ffff7a22c00 in MIDIStreamer::Play(bool, int) () at /usr/local/lib/libzmusic.so.1
#11 0x00007ffff7a27aee in ZMusic_Start () at /usr/local/lib/libzmusic.so.1
#12 0x0000555556063fbc in S_StartMusicPlaying(ZMusic_MusicStream, bool, float, int)
    (song=0x55555dc982c0, loop=true, rel_vol=1, subsong=0) at /dev/shm/gzdoom/src/common/audio/music/music.cpp:217
#13 0x0000555556065cce in S_ChangeMusic(char const*, int, bool, bool)
    (musicname=0x55555edff22c "D_runnin", order=0, looping=true, force=false)
    at /dev/shm/gzdoom/src/common/audio/music/music.cpp:708
#14 0x0000555555d56803 in FLevelLocals::SetMusic() (this=0x555557085760 <level>)
    at /dev/shm/gzdoom/src/g_level.cpp:2279
#15 0x0000555555e4c5a1 in P_SetupLevel(FLevelLocals*, int, bool)
    (Level=0x555557085760 <level>, position=0, newGame=true) at /dev/shm/gzdoom/src/p_setup.cpp:441
#16 0x0000555555d51cfa in FLevelLocals::DoLoadLevel(FString const&, int, bool, bool)
    (this=0x555557085760 <level>, nextmapname=..., position=0, autosave=false, newGame=true)
    at /dev/shm/gzdoom/src/g_level.cpp:1185
#17 0x0000555555d518a0 in G_DoLoadLevel(FString const&, int, bool, bool)
    (nextmapname=..., position=0, autosave=false, newGame=true) at /dev/shm/gzdoom/src/g_level.cpp:1077
#18 0x0000555555d4fbd8 in G_InitNew(char const*, bool) (mapname=0x555557e87fcc "map01", bTitleLevel=false)
    at /dev/shm/gzdoom/src/g_level.cpp:555
#19 0x0000555555d4f6de in G_DoNewGame() () at /dev/shm/gzdoom/src/g_level.cpp:424
#20 0x0000555555d44339 in G_Ticker() () at /dev/shm/gzdoom/src/g_game.cpp:1149
#21 0x0000555555d337eb in TryRunTics() () at /dev/shm/gzdoom/src/d_net.cpp:1987
#22 0x0000555555d2389b in D_DoomLoop() () at /dev/shm/gzdoom/src/d_main.cpp:1288
#23 0x0000555555d29f2d in D_DoomMain_Internal() () at /dev/shm/gzdoom/src/d_main.cpp:3648
#24 0x0000555555d2a24e in GameMain() () at /dev/shm/gzdoom/src/d_main.cpp:3678
#25 0x00005555559e418b in main(int, char**) (argc=1, argv=0x7fffffffdff8)
    at /dev/shm/gzdoom/src/common/platform/posix/sdl/i_main.cpp:194

g_cond_wait is waiting for something that doesn't happen.

**Comment by alexey-lysiuk** [comment]
It’s a known issue with FluidSynth. Switch MIDI device to TiMidity++ in Sound Options menu.
