### ISSUE TITLE
Suggestion: HIRES support for patches

### ISSUE THREAD

**Issue by r6d2** [coelckers/gzdoom#1362]
Haven't come across this subject after searching the reported issues.

The HIRES directory structure works quite well well you want to replace a whole texture with a higher resolution version. Scaling the texture seems to be taken care of by GZDoom so there's no need to mess with the texture definitions.

When you replace patches, however, you need to scale manually the texture definitions as well. I think it would be nice to have GZDoom handle this automatically.

Have you given any thought to this? Are there any plans to support such a feature?

Many thanks in advance.

**Comment by coelckers** [comment]
This isn't so easy. you cannot patch together textures of parts with different scaling. So, even if such patches were present, what should be done with them? The entire concept was deliberately left out when implementing hires content.

**Comment by r6d2** [comment]
Thanks for your feedback, Graf. I figured it wasn't easy as pie.

But in response to your question, the scenario I'm referring to would consist of all patches scaled by the same factor. Much like every HIRES texture package out there, which use the same scale factor for all textures. For instance 4x (DHTP), or 2x (Neural upscale).

So in such a case what the engine should do is to automatically apply the 4x factor to the texture definitions before passing them to the "patch together" part of the code.

The 4x factor (or whatever) could be determined at run time by simply reading the first patch found on HIRES and comparing it to the regular one with the same name found on the IWAD. (By dividing the HIRES version width by the regular width you get the 4x or whatever).

I hope what I'm explaining makes sense...
