### ISSUE TITLE
(Enhancement/Inconsistency) Make IsGrayed in OptionMenuSliderBase virtual

### ISSUE THREAD

**Issue by RicardoLuis0** [coelckers/gzdoom#1363]
`isGrayed` in `OptionMenuItemOptionBase` is virtual, but `IsGrayed` is not virtual in `OptionMenuSliderBase`, which caused a slight roadblock for me (necessarily solved via code duplication, but it's not an ideal solution)

**Comment by nashmuhandes** [comment]
PR has been merged, this issue can be closed
