### ISSUE TITLE
Problem with saving

### ISSUE THREAD

**Issue by x3003** [coelckers/gzdoom#1375]
Using gzdoom-x64-g4.6pre-199-g4bcea0ab7.
When saving a file multiple times as "1", without the quotation marks, gzdoom writes to a random slot, instead of the current (already saved) one. So it overwrites files that are also saved with other names.

Tried this with doom2/freedoom/wolfendoom.

**Comment by alexey-lysiuk** [comment]
Already reported it [here](https://forum.zdoom.org/viewtopic.php?t=72085).

**Comment by x3003** [comment]
Ok, thx for letting me know.
