### ISSUE TITLE
Czech language adjustments

### ISSUE THREAD

**Issue by MuadDib90** [coelckers/gzdoom#1376]
Hi there,
I am working in BoA team; primarily as a translator. I have come across some lines, that seemed odd to me, and are GZDoom engine related - not BoA language.csv. So, I wanted to ask for permission to access your _language.csv_ to go through it and, if necessary, make proper changes.

Can someone help me with it, please?

**Comment by alexey-lysiuk** [comment]
Request access to language spreadsheets [here](https://forum.zdoom.org/viewtopic.php?t=63737).

**Comment by MuadDib90** [comment]
Thanks.
