### ISSUE TITLE
UsePlayerStartZ

### ISSUE THREAD

**Issue by KappesBuur** [coelckers/gzdoom#1403]
Could this be extended to specify the speed of falling when used in a scenario without 3D floor?

**Comment by coelckers** [comment]
No. Speed of falling is just the effect of gravity. Adding hacks is not going to happen.

**Comment by Gaerzi** [comment]
You can [change gravity](https://zdoom.org/wiki/Gravity) in the starting sector through already-existing methods.

**Comment by KappesBuur** [comment]
Changing the gravity of the sector worked perfectly. Ty
