### ISSUE TITLE
[Vulkan] Player's appearance preview not updating after changing colors

### ISSUE THREAD

**Issue by manusaurio** [coelckers/gzdoom#1406]
## Description
Having _Preferred Rendering API_ set to _Vulkan_ screws up the way sprites are displayed in _Player Setup_: once a sprite is loaded in that menu, it won't change it again, even after you choose a different color. This can be tested by entering the menu, picking some different RGB values, and then changing your class.

Init log:
```
GZDoom g4.6.0-m - 2021-05-22 16:34:22 +0200 - SDL version
Compiled on May 24 2021

OS: Arch Linux, Linux 5.12.8-arch1-1 on x86_64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /usr/lib/gzdoom/gzdoom.pk3, 633 lumps
 adding /usr/lib/gzdoom/game_support.pk3, 2514 lumps
 adding ./HEXEN.WAD, 4270 lumps
 adding /usr/share/gzdoom/game_widescreen_gfx.pk3, 98 lumps
I_Init: Setting up machine state.
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Family 6, Model 94, Stepping 3
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device Built-in Audio Analog Stereo
  EFX enabled
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 141.65 ms
R_Init: Init Hexen refresh subsystem.
DecalLibrary: Load decals.
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading custom status bar definition.
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
Using video driver x11
Vulkan device: AMD RADV POLARIS11 (ACO)
Vulkan device type: discrete gpu
Vulkan version: 1.2.168 (api) 21.1.1 (driver)
Max. texture size: 16384
Max. uniform buffer range: -1
Min. uniform buffer offset alignment: 4
Resolution: 1920 x 1080

```

## How to reproduce
1. Set `vid_preferbackend` to `1` in the gzdoom.ini config file, then make sure the `playerclass` entry under `[Hexen.Player]` is set to anything but `Random`. Save the configuration and then launch GZDoom with Hexen as IWAD.
2. Enter the _Player setup_ menu. Do not change your class yet! Drag the color sliders to anything you'd like, you won't notice any difference.
3. Press space to look at the character's back. The sprites will be loaded with the color you set during the previous step.
4. Change the RGB values again, then change your class. The sprites for the class you see for the first time (during this session) will be displayed with that color.
5. You can keep changing your color and then your class or turn them around. Every sprite you saw to this moment won't be affected by your latest settings, they'll remain as the color they were loaded with.

**Comment by alexey-lysiuk** [comment]
This was already reported [here](https://forum.zdoom.org/viewtopic.php?t=72290).
