### ISSUE TITLE
double barreld shotgun although doom.wad

### ISSUE THREAD

**Issue by RicardoCapricciosa** [coelckers/gzdoom#1407]
with v4.6.0 when I load the ultimate doom.wad I can select the double barreld shotgun, but it is not displayed. Only a second press of "3" brings me the normal shotgun. This should not happen with the doom1 wad file.

**Comment by alexey-lysiuk** [comment]
Closed as [duplicate](https://forum.zdoom.org/viewtopic.php?t=72400).
