### ISSUE TITLE
Some settings are not saved

### ISSUE THREAD

**Issue by d9d6ka** [coelckers/gzdoom#1417]
Hi! I've found, that some options are not saved in the latest release version of GZDoom (4.6.0).

Specifically I'm trying to disable jumping and crouching.

I go to the `Gameplay options` and set `Allow jumping` and `Allow crouching` to `OFF`. Then I `save current settings`.
After GZDoom restarted these settings are set back to `Default`. And the Doom guy starts jumping while I'd like to play classic WADs in Vanilla-style.

When I peeked into the created `ini` file I didn't find any jumping or crouching options but the corresponding keybindings.

Mouse options are saved as expected, for example.

Thanks.

**Comment by Doom2fan** [comment]
It's behaving as expected. That's because the settings in the "gameplay options" menu are intentionally not saved.

**Comment by d9d6ka** [comment]
> It's working correctly. That's because the settings in the "gameplay options" menu are intentionally not saved.

Does it mean than I need **manually** disable these settings **every** time I start the game? 🤦 It's kinda strange...

**Comment by Gaerzi** [comment]
You can just unbind your jump and crouch buttons if you really want.

The default setting is to allow unless it's disallowed by MAPINFO.
