### ISSUE TITLE
Gzdoom crashes system (Gpu hang)

### ISSUE THREAD

**Issue by user85475485** [coelckers/gzdoom#1421]
![signal-2021-06-29-210038_002](https://user-images.githubusercontent.com/64977518/123853298-97439600-d91d-11eb-9b42-7ba128f4a009.jpg)
![signal-2021-06-29-210038_001](https://user-images.githubusercontent.com/64977518/123853307-9874c300-d91d-11eb-9f8d-1eb7789c1661.jpeg)

Hey
I dont know if this is the right place to report bugs but im encountering some issues.
When i play Gzdoom the game would eventually hang for a few seconds before massive glitching would occur. I can still move freely in the game. 
Is there any fix for that?
Thanks in advance.

The System Log shows a GPU hang error, i dont have any issues in other games and the OS runs stable
Sadly i couldnt attach any Gzdoom log because the entire System would lock up (Reboot required)
Im experiencing pretty much the same as this person ---> https://forum.zdoom.org/viewtopic.php?t=58400 the CPU is not overheating tho

Specs:

Gzdoom 4.6 (Latest Version Downloaded today)
I5 4460
8GB Ram
Intel Hd Graphics
Ubuntu 21.04 (Bug also occurs on 20.04 LTS)

**Comment by madame-rachelle** [comment]
This is something I don't think we can address directly - the problem occurs between the API layer and the hardware stack. That's not something GZDoom can touch directly, so if a driver is doing something funky there's nothing GZDoom can do.

The only suggestion I can give you is to update Mesa. Ubuntu always has an outdated version of it. https://itsfoss.com/install-mesa-ubuntu/

**Comment by madame-rachelle** [comment]
Furthermore you may also be getting hit by this bug: https://forum.zdoom.org/viewtopic.php?f=50&t=70121 but it's Windows specific. Nevertheless, if this is the same bug, then the issue is much more likely to be in the hardware.

**Comment by user85475485** [comment]
Thanks for the replies!
It really seems to be an Hardware issue or some weird Driver f*ckery
Installing newest Mesa and even reinstalling Xorg and xorg-video didnt help too
