### ISSUE TITLE
gzdoom not working anymore

### ISSUE THREAD

**Issue by x3003** [coelckers/gzdoom#1425]
After updating gzdoom-x64-g4.7.0pre-67-g92a92b130 to gzdoom-x64-g4.7.0pre-69-gfbf5b9f2d, the program doesn't work anymore w/ blade of agony / doom2 / freedoom (and others ?!).
Seems there's an error in line 56.

![gzdoom_fd](https://user-images.githubusercontent.com/77861029/124660153-1c8ef380-dea6-11eb-8fe2-4f67ce67e9b4.jpg)

**Comment by mc776** [comment]
That line should say "default" not "defaults".

**Comment by x3003** [comment]
Working now.
