### ISSUE TITLE
Detect REKKRSA.WAD as IWAD version of REKKR

### ISSUE THREAD

**Issue by Some1NamedNate** [coelckers/gzdoom#1449]
REKKR, a total conversion of The Ultimate Doom, is available as an IWAD under the filename `REKKRSA.WAD` complete with a `DEHACKED` lump. However, for some reason, GZDoom does not detect it and thus ignores and does not list it in the IWAD launcher.

Can you please add `REKKRSA.WAD` to GZDoom's IWAD database?

For reference, have look at the [homepage](http://manbitesshark.com/).

**Comment by RealRexen** [comment]
Rename REKKRSA.WAD to REKKRSA.ipk3 and it should appear

![image](https://user-images.githubusercontent.com/18408903/128268414-e2912875-d007-4ba8-8cfb-16d32bed7b8a.png)

**Comment by SanyaWaffles** [comment]
You can rename it REKKRSA,iwad and it'll do the same thing. IPK3 is for zip files, not WADs

**Comment by Some1NamedNate** [comment]
I just found out that the file signature for REKKRSA.wad is `PWAD` instead of `IWAD`.

**Comment by alexey-lysiuk** [comment]
GZDoom doesn’t care about WAD signature. As long as IWAD has `.iwad`/`.ipk3`/`.ipk7` extension and contains `IWADINFO` lump, it will be detected as IWAD.
So, there is no reason to do anything here. Support for custom IWADs was added because we didn’t want to change internal definitions anymore.
