### ISSUE TITLE
[2.8pre-1190] Projectiles bounce improperly off Actor tops

### ISSUE THREAD

**Issue by coelckers** [coelckers/gzdoom#145]
http://forum.zdoom.org/viewtopic.php?f=2&t=47853

**Comment by MajorCooke** [comment]
I think [this](https://github.com/coelckers/gzdoom/issues/133) now supercedes this one.

**Comment by coelckers** [comment]
I need to check both to be certain.

**Comment by coelckers** [comment]
Can't fix without making a complete mess of it.
