### ISSUE TITLE
[Feature Request] A launch parameter to supress warnings meesages in Console/Boot Log.

### ISSUE THREAD

**Issue by PRinceBhai** [coelckers/gzdoom#1450]
Because some mods are made to be compatible with lots of other GamePlay mods. The engine points out every non existing actor and such other "warnings" and causes a significant delay in boot up of the game. If There can be a switch like "-noWarning" or -noErrors" which can toggle these, then I'd be more than grateful.

**Comment by madame-rachelle** [comment]
This has been suggested before and rejected. The warnings are there for a reason and they are not meant to be ignored. This particular use case is simply not a viable reason for accepting the suggestion as-is. If the existence of actors is meant to be optional, then something will need to be made for GZDoom separately, to handle that.

**Comment by PRinceBhai** [comment]
> The warnings are there for a reason and they are not meant to be ignored.
But I'm not asking them to be completely ignored, i understand their importance, but to a simple gamer or a Doomer they are nothing but nuisance.

> Something will need to be made for GZDoom separately, to handle that.
The mods that me and my friend are trying to play are only for GZDoom.

**Comment by madame-rachelle** [comment]
I haven't closed this outright yet because I am not 100% sure if the overarching opinion on this topic has changed, yet.

There is some merit to what you are asking, but I think it needs to be addressed differently than the way you are suggesting. It should be possible for gameplay mods to add shims for optional actors, rather than adding in the ability to have the messages just not be printed.

**Comment by Gaerzi** [comment]
Maybe something like the "optional" keyword that exists in TEXTUREx?

    Like Actor Foo : Bar replaces Baz 1337 optional
    {
       <code here>
    }

When the optional keyword is encountered, if the inherited actor doesn't exist, the the entire actor is silently ignored.

**Comment by madame-rachelle** [comment]
Yes - that - or the ability to define shims for optional actors that are meant to be replaced with real ones so that GZDoom does not print errors.

**Comment by coelckers** [comment]
Whatever makes sense here, suppressing warnings is not and will never be an option. That will only lead to broken mods.
