### ISSUE TITLE
[BUG] I am unable to compile GZDoom

### ISSUE THREAD

**Issue by N0-p3** [coelckers/gzdoom#1456]
### GZDoom version

4.6.1

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

As I compile GZDoom with "cmake CMakeList.txt" it outputs this error
```
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Looking for fts_set
-- Looking for fts_set - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Using system zlib, includes found at /usr/include
-- Looking for backtrace
-- Looking for backtrace - found
-- Using internal asmjit
-- Using system jpeg library, includes found at /usr/include
-- Using system bzip2 library, includes found at /usr/include
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of 0i8
-- Check size of 0i8 - failed
-- Check size of 0l
-- Check size of 0l - done
-- Check size of 0ll
-- Check size of 0ll - done
-- Check size of char
-- Check size of char - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of void *
-- Check size of void * - done
-- Check size of __int64
-- Check size of __int64 - failed
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find ZMusic (missing: ZMUSIC_LIBRARIES ZMUSIC_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindZMusic.cmake:21 (find_package_handle_standard_args)
  src/CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/nope/Desktop/Doom PB 3.0/gzdoom/build/CMakeFiles/CMakeOutput.log".
See also "/home/nope/Desktop/Doom PB 3.0/gzdoom/build/CMakeFiles/CMakeError.log".
 
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Clone the repo
2. cd build
3. cmake ..

### Your configuration

```ini
I don't have config files, I can't even install it
```

### Provide a Log

[CMakeOutput.log](https://github.com/coelckers/gzdoom/files/7085649/CMakeOutput.log)
[CMakeError.log](https://github.com/coelckers/gzdoom/files/7085650/CMakeError.log)

**Comment by coelckers** [comment]
You must set up the ZMusic dependency to compile. Without that it indeed cannot compile.

**Comment by N0-p3** [comment]
How come it isn't in the wiki ? https://zdoom.org/wiki/Compile_GZDoom_on_Linux I don't see any place where ZMusic is mentionned on this page.
Compile GZDoom on Linux - ZDoom Wiki<https://zdoom.org/wiki/Compile_GZDoom_on_Linux>
How to increase Zandronum/GZDoom OpenGL FPS. Commands beginning with "sudo" will require temporary superuser privileges. Run Zandronum/GZDoom, start a new game, open console and type vid_fps 1, see how many FPS are displayed and exit Zandronum/GZDoom.. If you do not use Intel graphics, go to #Disable Vertical Synchronization for Zandronum/GZDoom.. Enable SandyBridge's New Acceleration
zdoom.org


________________________________
De : Christoph Oelckers ***@***.***>
Envoyé : 31 août 2021 13:34
À : coelckers/gzdoom ***@***.***>
Cc : Nycola Plaisance ***@***.***>; Author ***@***.***>
Objet : Re: [coelckers/gzdoom] [BUG] I am unable to compile GZDoom (#1456)


You must set up the ZMusic dependency to compile. Without that it indeed cannot compile.

**Comment by Gaerzi** [comment]
Unfortunately, the instructions on the wiki are not necessarily up to date.
