### ISSUE TITLE
[BUG] Can't kill the Arch-vile in Plutonia level 27

### ISSUE THREAD

**Issue by Froyd1** [coelckers/gzdoom#1458]
### GZDoom version

4.6.1

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 8

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Final Doom, level 27 of Plutonia, I am unable to kill the Arch-vile, without cheats, in the stone like tower, as it keeps resurrecting the chain gunner. I have fired more than a hundred rockets at it, and no luck, as I have tried all kinds of angle shots. I saw other people on YouTube killing it successfully, but only on different source ports. I was wondering if its this source port? Is there a way to fix this bug by removing the Arch-vile or a better way of defeating it?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by Gaerzi** [comment]
I managed to kill it from this place:
![Sector #126](https://i.imgur.com/LWTJgQZ.png)

**Comment by Froyd1** [comment]
I managed to kill it at this angle shot (see screenshot below) and it took one hundred rocket shots, which is insane! I also had to keep reloading my save too, and it finally died after shooting in the same spot. Sweet, I too tried that angle to kill the Arch-vile! How many rocket shots did it take you to kill it?
![Screenshot_Doom_20210906_091858](https://user-images.githubusercontent.com/80136749/132244779-2473d485-181b-47f5-809f-d445c9d7c6b2.png)

**Comment by OrdinaryMagician** [comment]
This might just be due to the fact explosions aren't infinitely tall by default in GZDoom.

**Comment by Froyd1** [comment]
Maybe true, and also explains it takes a hundred rockets or more to kill the Arch-vile in that stone tower. A suggestion for the next version for GZDoom, is to somehow make it easy to kill the Arch-vile by using less than a hundred rockets or more?

**Comment by Architector4** [comment]
I can confirm on Arch Linux and with gzdoom recently built from git. The menu can be resized to be made bigger, but its minimal size insists to keep all entries visible. I imagine that having IWADs than screen height allows would make this menu a chore to use.

![menu](https://user-images.githubusercontent.com/23612841/132843438-40da45cd-4991-437d-907a-2a8afe77e1de.png)

**Comment by Architector4** [comment]
As a possible workaround, you can run gzdoom as `GDK_DPI_SCALE=0.5 gzdoom`

The environment variable tells GTK to scale all text half as small, which makes it less readable, but ends up making the entire menu a bit smaller, which may help.

You could also try messing with GTK theming to reduce margins and such as much as possible, but I'd rather just ask for a scrollbar.

**Comment by coelckers** [comment]
As far as I remember you are not even supposed to be able to kill that Arch Vile at all. The entire setup was made so that it endlessly resurrects the chaingunner to be a constant unkillable threat. Granted, the setup there isn't foolproof and it is possible to get lucky with a few rockets, If this is so important to you, flip the compatibility option that re-enables vanilla explosion behavior being height-unwarare.

**Comment by ryanmusante** [comment]
What is the best compatibility option to leave for most maps? Default? Doom strict?

**Comment by Gaerzi** [comment]
Doom (Strict) is a bad idea, it'd definitely break a lot of Boom and ZDoom maps, it's the "halp I can't open this door" setting. That's why there are different presets for "Doom" and "Doom (Strict)", the former is safer to use in general than the latter. Same for Boom and Boom (Strict).

But you can also pick and choose. I'd suggest keeping default and just re-enabling vertical explosions.

**Comment by coelckers** [comment]
The option in question is not part of the Doom preset, but only of Doom (strict). It may be better to flip the option itself in the compatibility menu.

**Comment by axredneck** [comment]
As i can remember there are crushers that will kill the archviles when you reach exit.

**Comment by Blue-Shadow** [comment]
> 
> 
> As i can remember there are crushers that will kill the archviles when you reach exit.

Not in this map. You're probably thinking of [MAP15](https://doomwiki.org/wiki/MAP15:_The_Twilight_(The_Plutonia_Experiment)).
