### ISSUE TITLE
[BUG] "Invert sprite sorting" compatibility flag causes odd sprite shadows

### ISSUE THREAD

**Issue by cncz42** [coelckers/gzdoom#1477]
### GZDoom version

4.7.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### If Other OS, please describe

Tested on arch linux as well

### Relevant hardware info

Ryzen 9 3900x, RTX 2080ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Enabling the invert sprite sorting compatibility flag causes sprite shadows to appear over, rather than behind, applicable sprites. I am unsure if this is an intended consequence of the flag but it's nonetheless somewhat of an issue.
No flag:
![Screenshot_Doom_20211004_171222](https://user-images.githubusercontent.com/49820257/135942432-66d9388a-de15-4fd1-8999-b49f99b8ee1c.png)
With flag:
![Screenshot_Doom_20211004_171236](https://user-images.githubusercontent.com/49820257/135942449-93c9f7c0-6175-4d4b-acbf-4564886322e9.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Enable sprite shadows on monsters
2. Enable the "invert sprite sorting" compatibility flag
3. Play game

### Your configuration

```ini
https://gist.github.com/cncz42/584aed76656b3a95fc2a52fb14ca69a9#file-gzdoom-test-ini
```

**Comment by coelckers** [comment]
fixed in 8d9d56c339c5ac0b9efdee583b684498e74e531b
