### ISSUE TITLE
[BUG] Severe performance drop on linux 5.14, clock_gettime flood

### ISSUE THREAD

**Issue by Vladimir-csp** [coelckers/gzdoom#1479]
### GZDoom version

GZDoom g4.7.0 - 2021-09-21 22:08:33 +0200 - SDL version

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debian Testing

### Relevant hardware info

AMD Ryzen 3 5300U, AMD RENOIR (DRM 3.42.0, 5.14.0-2-amd64, LLVM 12.0.1)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GZDoom runs radically slower with complex content on Linux 5.14 compared to Linux 5.10. This does not seem to be related to graphics and renderer (gl, gles, vulkan make no difference). 

Strace output for gzdoom on 5.14 has LOTS of these spammed all over:
```
clock_gettime(CLOCK_MONOTONIC, {tv_sec=55, tv_nsec=7221346}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=55, tv_nsec=7248727}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=55, tv_nsec=7275614}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=55, tv_nsec=7303488}) = 0
```
Heaviest occurrences are when the map is running. 
Number of clock_gettime calls appears to be proportional to content complexity. This performance drop is unnoticeable on vanilla doom, or even with Project Brutality on simple maps. But with complex maps such as Cchest2 MAP15 clock_gettime calls overwhelm CPU and appear to be the only thing gzdoom is doing, resulting in ~1 FPS slideshow.

Strace for gzdoom on 5.10 has none of those calls, the game runs smoothly.

### Steps to reproduce the behaviour.

Explain how to reproduce
clock_gettime flood is reproducible just by launching the game.
For it to affect performance launch something heavy:
1. Install Project Brutality, Cchest2 (https://github.com/pa1nki113r/Project_Brutality/archive/refs/heads/master.zip, https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/cchest2)
2. Load MAP15

### Your configuration

```ini
[Global.Autoload]
Path=Project_Brutality-master.zip
Path=Cchest2.wad
```

### Provide a Log

Nothing extra or suspicious is in the output of gzdoom.
Some stats on strace (scenario: run gzdoom, load saved game on map15, run for 2-3 seconds):
```
# on Linux 5.10
$ grep -Eo 'clock_gettime\([^ ]+' tmp/strace_5.10 | sort | uniq -c | sort -n

# on Linux 5.14
$ grep -Eo 'clock_gettime\([^ ]+' tmp/strace_5.14 | sort | uniq -c | sort -n
    526 clock_gettime(CLOCK_MONOTONIC_RAW,
 558925 clock_gettime(CLOCK_MONOTONIC,

# on Linux 5.14 without PB, on map01
$ grep -Eo 'clock_gettime\([^ ]+' tmp/strace_5.14_nopb_map01 | sort | uniq -c | sort -n
    595 clock_gettime(CLOCK_MONOTONIC_RAW,
  38397 clock_gettime(CLOCK_MONOTONIC,

# on Linux 5.14 with PB, on map01
$ grep -Eo 'clock_gettime\([^ ]+' tmp/strace_5.14_pb_map01 | sort | uniq -c | sort -n
    341 clock_gettime(CLOCK_MONOTONIC_RAW,
 208599 clock_gettime(CLOCK_MONOTONIC,
```

**Comment by coelckers** [comment]
Oh my. This reminds me of something that happened many years ago when ZDoom switched its internal profiling code from the TSC to Windows's QueryPerformanceCounter. The end result was that GZDoom became creepingly slow because its benchmark timer ended up calling this tens of thousands of times per frame and I had to roll out my own low level timer.
 Find the story here: https://forum.zdoom.org/viewtopic.php?f=7&t=18506

**Comment by Cacodemon345** [comment]
It's hitting other Linux 5.14 users too. `WATCHDOG_MAX_SKEW` was halved to 50000 nanoseconds from 100000 nanoseconds in this release which leads to higher chance of TSC recalibration and therefore failures and thus increasing chances of switching to HPET.

**Comment by octotherp** [comment]
* It looks like most Lenovo Ryzen products are affected https://forums.lenovo.com/t5/Other-Linux-Discussions/Unusable-TSC-on-P14s-and-X13-with-the-latest-LTS-kernel/m-p/5064905
* This is not a kernel problem but a bios one https://bugzilla.kernel.org/show_bug.cgi?id=215037
* Forcing tsc with kernel boot param `tsc=reliable` while indeed improves performance is not a solution as it makes system unstable, several problems pops out immediatly, at least in my case. So kernel is in the right ditching tsc.

So i've checked the code and decided to try to override CLOCK_MONOTONIC with CLOCK_MONOTONIC_COARSE via LD_PRELOAD and it works great. Time resolution is 1ms with 5.15 kernel.

<details>
<summary>preloaded code</summary>

```c
#define _GNU_SOURCE

#include <time.h>
#include <dlfcn.h>

int (*o_clock_gettime)(clockid_t, struct timespec*);
void init(void){
    o_clock_gettime = dlsym(RTLD_NEXT, "clock_gettime");
}

void __attribute__((constructor)) init();

inline int clock_gettime(clockid_t clockid, struct timespec *tp){
    return (*o_clock_gettime)(CLOCK_MONOTONIC_COARSE, tp);
}
```

</details>  

While hpet is "slow" it benchmarks 780k calls per second. I believe game logic is tick-based and does not need nowhere near hundreds of thousands of gettime calls per second?

**Comment by OrdinaryMagician** [comment]
Yeah, now that I switched to an AMD CPU I'm seeing this issue popping up. booting with `tsc=reliable` has definitely worked for me and I haven't really had any issues so far? Especially because tsc is nevertheless working fine on some occasions and not in others (almost like it has some hiccups depending on cold boot / reboot conditions).
