### ISSUE TITLE
[Feature] RandomSpawner Seeds/CustomSpawners

### ISSUE THREAD

**Issue by mattbratt11** [coelckers/gzdoom#1483]
### GZDoom version

GZDoom 4.7.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Would it be cool if RandomSpawner has seeds you can set via GZDoom's Gameplay Menu?
With this, I don't have to worry about Rando's Revenge aka Hardcoded and Underappreciated RNG Treachery aka The H.U.R.T. of Rando.

**Comment by coelckers** [comment]
Sorry, this is beyond the scope of what the engine is supposed to do. Clear DIY material.
