### ISSUE TITLE
DamageMobj virtual function

### ISSUE THREAD

**Issue by MajorCooke** [coelckers/gzdoom#149]
For actors, it calls their version of DamageMobj that can be overridden.

**Comment by MajorCooke** [comment]
Also I don't know if I can assign a tag to it or if that's just something you do yourself, Graf.

**Comment by MajorCooke** [comment]
If I recall correctly this is just going to call P_DamageMobj directly while having everything else do something like CallDamageMobj, correct?

**Comment by coelckers** [comment]
Moved to Mantis tracker
