### ISSUE TITLE
[Feature] Supersampling

### ISSUE THREAD

**Issue by NineKain** [coelckers/gzdoom#1496]
### GZDoom version

gzdoom-x64-g4.8pre-56-g199558189

### What Operating System are you using?

Windows 10

### Relevant hardware info

R5 5600x, 3060ti, 16gb RAM

### Is your feature request related to a problem? Please describe.

I'd love to have Supersampling in GZDoom, in high end machines, it completely eliminates aliasing without any performance downside, and looks better than multisampling, but there's no reason why we couldn't have both.

### Describe the solution you'd like

Have a supersampling option below the Multisampling one.

### Describe alternatives you've considered

Forcing it thru NVIDIA Control Panel, didn't seem to do much.

**Comment by caligari87** [comment]
If I understand what you're asking, GZDoom already includes a feature like this. Please try setting the "Scale Factor" to 2.0 in the "Scaling Options" menu. This will render the game at 2x and then scale it down to match your default resolution.

![image](https://user-images.githubusercontent.com/6425795/140970646-526fbdbf-5e05-48b1-b6d5-8a5eb4c03e35.png)
