### ISSUE TITLE
[BUG] Infinite loop in stair builder

### ISSUE THREAD

**Issue by kraflab** [coelckers/gzdoom#1504]
### GZDoom version

GZDoom v4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The stair building code tracks the previous sector, in order to make sure it doesn't build the same stair twice in a row. But it only remembers the last one, so nothing stops it from building the same sector infinitely, depending on the orientation of the steps. This is in contrast to hexen, which keeps track of all the stairs that have been built and will ignore any already in the chain (using the `validcount` variable).

I noticed this while implementing the same code in dsda-doom. The relevant section is here: https://github.com/coelckers/gzdoom/blob/70ea671f01eb1f3cba2c574d5d2af90a2171adf8/src/playsim/mapthinkers/a_floor.cpp#L670-L687

Since dsda-doom inherits the hexen code, it uses the validcount to avoid this situation: https://github.com/kraflab/dsda-doom/blob/f0e9b6714c2f7970889fa157a57d67b2baeeda7e/prboom2/src/p_floor.c#L1698-L1711

Not sure if this is just a known and accepted situation, but wanted to point it out.

### Steps to reproduce the behaviour.

A simple configuration is a square cut into 4 quarters. Top left and bottom right have special 27. Top right and bottom left have special 26. Connect to line special 27. Upon activation the game will freeze in an infinite loop building the stairs forever. A basic wad is attached, you can just walk forward to trigger it. The line builds BL, which builds BR, which builds TR, which builds TL, which begins the process again at BL.

[infloop.zip](https://github.com/coelckers/gzdoom/files/7500673/infloop.zip)

### Your configuration

```ini
Default
```

**Comment by coelckers** [comment]
Fixed in 63fa01205f9b111c8e6b27b54fe736f834b6b807
