### ISSUE TITLE
GetName(String) For ZScript

### ISSUE THREAD

**Issue by MajorCooke** [coelckers/gzdoom#151]
For classes and actors, gets the name of the actor if using GetName. Or if GetNameString, returns it as a string instead.

**Comment by coelckers** [comment]
Added GetClassName. No need for two functions.

**Comment by MajorCooke** [comment]
Oh, they can translate from string to name automatically?

Also, ACTION_RETURN_**INT**?

**Comment by coelckers** [comment]
Internally a name is just an int, and ACTION_RETURN_NAME does not exist...

**Comment by MajorCooke** [comment]
Okay. But this still makes me wonder if there's any way to translate a name to a string and/or back again.

**Comment by coelckers** [comment]
Names can normally be assigned to strings and vice versa without using any type cast, and in case it's ambiguous a type cast will clear that up.
