### ISSUE TITLE
GLDEFS Glow & Animated Textures.

### ISSUE THREAD

**Issue by XxMiltenXx** [coelckers/gzdoom#152]
See here: http://forum.drdteam.org/viewtopic.php?f=24&t=7441

**Comment by coelckers** [comment]
This will require a bit of reworking. The original glow feature just calculated the info from the texture and with that approach having different glows for animated textures looks bad, it needs to be different for those and explicitly defined ones.

**Comment by coelckers** [comment]
Done, because adding glows as UDMF property required reworking this anyway.
