### ISSUE TITLE
[Feature] Supporting DoomEdNums & SpawnNums > 32k

### ISSUE THREAD

**Issue by Lemon-King** [coelckers/gzdoom#1522]
### GZDoom version

GZDoom 4.8pre-89-g2ce5b49ca

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 11

### Relevant hardware info

NVidia, AMD CPU, 32 GB System Ram

### Is your feature request related to a problem? Please describe.

DoomEdNums only seems to support IDs up to 32k.
It would be useful to allow higher ranges for further mod support.

### Describe the solution you'd like

Allow DoomEdNums/SpawnNums to use ids > 32k.

**Comment by coelckers** [comment]
DoomEdNum is a 16 bit value which also needs to support negative numbers. There's really no good point increasing the range of  numbers as doing so can only be done by using more memory for it.

**Comment by Gaerzi** [comment]
Why would you need more than 32k editor numbers anyway?

**Comment by Lemon-King** [comment]
I was organizing ids with a mod and ran across the issue when I went above 32k.

**Comment by mc776** [comment]
I'm guessing this is one of those things where you've got like 11000-12000 is for weapons or whatever... how many categories were you trying to have and what's the biggest number of entries for a given category?

**Comment by Lemon-King** [comment]
Sorta,
HXDD generates a list of entities based grouping: https://github.com/Lemon-King/HXDD/blob/main/src/main/java/lemon/hxdd/ActorFactory.java#L150
First is the compatibility list, which is a combination of ids between Heretic and Hexen with shared spawners for ids that overlap.
Followed by Heretic ids ranging from 11000+, then by Hexen ids from 22000+ which I set up for some experiments.

This isn't exactly optimized, where by using any skipped ids and possibly could have not even hit the upper limit.
