### ISSUE TITLE
[BUG] lzma2 solid compressed addon = game stuttering (during textures loading imho)

### ISSUE THREAD

**Issue by necros2k7** [coelckers/gzdoom#1530]
### GZDoom version

latest nightly

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Relevant hardware info

e5-2690, gtx950

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

after running compressed addon it makes freezes during gameplay

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  repack Re-exhumed addon to 7z lzma2 solid
2. play it
3.

**Comment by alexey-lysiuk** [comment]
If you are using solid compression, you must be aware of its implications. It's not possible to have the highest compression ratio and the lightning-fast decompression speed at the same time.
Engine is accessing files one by one, and this is a pure contradiction to the idea of solid compression.

**Comment by necros2k7** [comment]
maybe make an option to extract files to system tmp folder  / ramdrive and load it from there?
