### ISSUE TITLE
Intermission-enabling flag for MAPINFO/cluster

### ISSUE THREAD

**Issue by jewalky** [coelckers/gzdoom#154]
Basically, this thread. http://forum.zdoom.org/viewtopic.php?f=15&t=54764
Is this ok to implement?

**Comment by coelckers** [comment]
I'm not sure this is possible with how hubs are being handled. Of course if you manage to get it working yourself I'd gladly accept it.

**Comment by jewalky** [comment]
https://github.com/coelckers/gzdoom/pull/157
