### ISSUE TITLE
[BUG] OpenGL Issues with transparency in TEXTURES sprites

### ISSUE THREAD

**Issue by basedSkeleton** [coelckers/gzdoom#1550]
### GZDoom version

GZDoom g4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Ubuntu 20.04 LTS

### Relevant hardware info

11th Gen Intel® Core™ i5-11320H @ 3.20GHz × 8, Mesa Intel® Xe Graphics (TGL GT2)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you include graphics with transparent pixels in a zdoom TEXTURES file, they will cut into any graphic behind it. The bug does not occur on the Software or the TrueColor Software renderer.
What the image should look like: (from the TrueColor Software Renderer)
![Screenshot_Doom_20220216_180317](https://user-images.githubusercontent.com/82617401/154391197-7e77a555-e64d-4c69-b491-4e10b902f2a0.png)
What it looks like on OpenGL:
![Screenshot_Doom_20220216_180330](https://user-images.githubusercontent.com/82617401/154391320-c9dfef7b-1c47-4eba-9217-e9e7cd9e92c7.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Select the OpenGL Hardware Renderer in your GZDoom settings
2. Load [this pk3](https://www.mediafire.com/file/2cl981ijlg3k5b8/test.pk3/file) 
3. Spawn a zombieman and notice that there are holes at the edges of the body parts

### Your configuration

https://gist.github.com/basedSkeleton/82566627c6d7d1a10c0d3a1cdb027f87

### Provide a Log

https://gist.github.com/basedSkeleton/9b76ce5cfd4e24cfd5ddfdba41a1859b

**Comment by coelckers** [comment]
You are using it wrong. If you want to overlay patches with alpha channels you have to select an appropriate style for that. The default style just copies the patch's pixels, including alpha.

If you add 'style overlay' to all your patches it should do what you want.
