### ISSUE TITLE
[BUG] super shotgun will not switch out after reaching 1 shell

### ISSUE THREAD

**Issue by tm512** [coelckers/gzdoom#1556]
### GZDoom version

g4.8pre-123-g25f28c4b5

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In recent git versions of GZDoom, when a WAD using a dehacked patch is loaded, the super shotgun will not switch away for another weapon if the player has 1 shell remaining. Instead, it will stay up, and will go through the normal firing animation without actually firing any hitscan attacks or consuming ammo. This issue does not occur when no dehacked patch is loaded (i.e. while just playing Doom 2).

I used `git bisect` and was able to determine that this bug was introduced in commit 25f28c4, relating to MBF21's `A_ConsumeAmmo` codepointer.

### Steps to reproduce the behaviour.

To easily reproduce
1. Load a WAD with a dehacked patch (I used Ancient Aliens for my testing) and start a game
2. `give SuperShotgun; give Shotgun` in console
3. Fire once with the shotgun, switch to SSG, and keep firing

**Comment by coelckers** [comment]
Are you sure it was that commit? It is totally unrelated to the weapon firing code being used here.

**Comment by tm512** [comment]
I double-checked just in case I messed something up when bisecting, and yeah, I'm as sure as I can be. In commit `00d4442` the SSG swaps out as expected, but switching over to `25f28c4`, the very next commit, introduces this issue.

**Comment by coelckers** [comment]
fixed in d0e1aea273caae5c58500f2df699c444e3ecd218

Yes, it was this commit, I was confused because I didn't spot the actual error in there immediately.
