### ISSUE TITLE
ExplodeMissile virtual function

### ISSUE THREAD

**Issue by Cherepoc** [coelckers/gzdoom#156]
Should be much more flexible than hit master/target/tracer flags.

**Comment by coelckers** [comment]
For hitting actors this already exists in the form of SpecialMissileHit. That function can even decide if the missile is supposed to explode or not.

**Comment by Cherepoc** [comment]
Sorry, should've clarified what I want to achive with it. I want to make projectiles transform into non-projectiles if they hit anything they cannot damage (floors, walls, solid decorations, actors of same species as the shooter). So, ideally, I want to use the function that is called when the projectile is about to explode, and do some checks there - did it hit actor or something else, what kind of actor that was, etc. SpecialMissileHit is not the function I'm looking for because it's not called when missile hits wall/floor, and also precisely because it is called to decide if the missile should explode at all - that's something I want to be decided before my logic.

**Comment by MajorCooke** [comment]
+USEBOUNCESTATES is your solution in this case. Set it up so it bounces off of floors/walls/ceilings so the moment it hits something, it will do x/y/z without killing the missile.

**Comment by Cherepoc** [comment]
I know I can use that, but this is a workaround. I'd like to have a cleaner solution, if possible.
I can try do a PR myself, unless virtualizing this function has downsides.

**Comment by MajorCooke** [comment]
There most likely will be.

If anything, make it so SpecialMissileHit is called with a null victim actor upon hitting geometry. That should be simple enough to accomplish.

**Comment by Cherepoc** [comment]
I'll just stick to hittracer for the time being.
As for PR, turns out ExplodeMissile is not a member of Actor or Thinker, unlike all of the exported virtual functions. So is DamageMobj, so I'll see how it will be handled.
