### ISSUE TITLE
[Question] How much of this is based on the Doom engine?

### ISSUE THREAD

**Issue by guy4261** [coelckers/gzdoom#1565]
Hello,

First of all, thank you for creating `gzdoom`!

My question is: how much of your code is based on the [original code by Carmack et al.](https://github.com/id-Software/DOOM)? Before I get into diffing etc. I thought to just simply ask.

I find it amazing how something created ~30 years ago is still being used today (none of my code does...). Thinking a bit more about it, I figured the WADs are in use (art, sounds, maps) - but I wonder if the engine itself is still used or did your write everything from scratch (=loading data from the WAD files and then doing the rest).

Thanks!

**Comment by coelckers** [comment]
That code is still the core of most gameplay related parts, but they have undergone significant changes over time. Diffing with the original Doom source won't get you far - the fundamentals are still the same, but the code is simply too different as a whole - there have been feature additions, generalizations of certain deatils, fixed point math was replaced with floating pont math, Procedural C code was replaced with C++, and lots more.
