### ISSUE TITLE
[Feature] Why there are neutral and object on gender?

### ISSUE THREAD

**Issue by Nic-Usor** [coelckers/gzdoom#1576]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Why a count of madness include neutral and object in gender option? There are 2 genders: male and female.

**Comment by MajorCooke** [comment]
Simple. Maybe they're androids or terminators like Zero Tolerance mod and they want that to reflect it. Perfectly valid reason to keep them.
