### ISSUE TITLE
PunchDagger is silent when punching an enemy [bug]

### ISSUE THREAD

**Issue by FishyClockwork** [coelckers/gzdoom#158]
I hope I'm posting in the right place.

For some reason when punching a target no sound is played.
The issue seems to be this: https://github.com/coelckers/gzdoom/blob/master/wadsrc/static/zscript/strife/weapondagger.txt#L59
Changing S_Sound to A_PlaySound seems to fix it.

**Comment by FishyClockwork** [comment]
One question. How do I assign this the bug label?

**Comment by alexey-lysiuk** [comment]
Only owner or collaborator can assign labels, milestones, etc.

**Comment by coelckers** [comment]
This certainly should have read A_PlaySound, I must have missed this part when converting. S_Sound is the function for playing unpositioned sounds.
