### ISSUE TITLE
[Feature] Sharp Bilinear/Trilinear Texture Interpolation/Filtering

### ISSUE THREAD

**Issue by Hydra-Spectre** [coelckers/gzdoom#1586]
### GZDoom version

GZDoom v4.7.1

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 11

### Relevant hardware info

AMD Ryzen 3400G, Radeon Vega 11 iGPU, 8GB RAM

### Is your feature request related to a problem? Please describe.

I get frustrated with how filtering darkens and smears the artwork when turned on.
However, I am also dissatisfied with turning off filtering because it introduces distracting shimmering to the 2D pixel art (such as weapon bobbing and scrolling text in some mods), where there are uneven pixels.
This basically gives me a Catch-22. I want sharp (or mostly sharp) pixels but I do not want uneven pixel shimmering on 2D elements.

This is especially noticeable in the DOOM CE series of mods: Some assets were made in 200p (AI upscaled to 400p) while others were in 240p (AI upscaled to 480p), and they are all stretched vertically by 1.2x (400p becomes 480p, and 480p becomes 576p).
This introduces shimmering even in the title screens, which have scrolling text for credits.

### Describe the solution you'd like

A good fix for this issue I have would be implementing a new option of texture filtering to GZDoom: Sharp Bilinear/Trilinear Interpolation.
This is very similar to what RetroArch has as a sharp bilinear shader, and it has been implemented on many emulators and FPGA consoles.
It smooths out pixels to remove interpolation, but not too much as to blur and darken everything.

I think this approach would make it very good to retain the pixel art look of DOOM while eliminating shimmering.

**Comment by coelckers** [comment]
It is not this easy.
Texture filtering is a hardware feature so implementing a different algorithm requires circumventing this and doing it in the shader.
And that's a very complicated thing to do.
