### ISSUE TITLE
[Feature] Add raytracing

### ISSUE THREAD

**Issue by slavap** [coelckers/gzdoom#1589]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

If possible please add raytracing to GZDoom based on https://github.com/sultim-t/prboom-plus-rt
Because prboom+ is very limited comparing to GZDoom, so it is practically impossible to use hd texture packs, sprites, ...

### Add any other context or screenshots about the feature request here.

https://www.youtube.com/watch?v=i2Ld9YNUWls

**Comment by coelckers** [comment]
If it was that easy...

**Comment by mc776** [comment]
Did Github's "Issue Closed" always use the same purple as "PR Merged"? I got way too excited seeing this...

**Comment by MajorCooke** [comment]
I think it used to be red/grey.

**Comment by slavap** [comment]
@coelckers nobody said it is easy, but there is already working code, so it should be easier to accommodate it than write it from scratch.

**Comment by Gaerzi** [comment]
The codebase is different enough to make using that code not just a question of copy-paste. And more importantly, since the entire thing is hardware-dependent, that means that it can only be done by a developer who does have an RTX card to test that it works.

**Comment by slavap** [comment]
@Gaerzi yep, RTX card is needed of course.

**Comment by madame-rachelle** [comment]
I'll say again what I said on Discord about this discussion: To add to what Gaerzi said - we do not have *any* active developers who have an RTX card. And this isn't as easy as "just copy paste it in!!!!" - it simply does not work that way. The only developer who can do it for GZDoom right now is the one who already did it for prBoom and if he hasn't done it for GZDoom right now he's likely not interested. So - it's a waiting game until some capable GZDoom developer actually gets their hands on an RTX card. And you know what they say: GOOD FUCKING LUCK WITH THAT! (at least for another year or two if not more)

**Comment by slavap** [comment]
@madame-rachelle RTX card is not a problem, you can ask for donations and I bet the needed amount will be collected quickly (if the goal will be adding raytracing). Have no idea why it should be a year or more if you have already a working code on hand. And this code for the similar renderer.

**Comment by madame-rachelle** [comment]
You can ask for donations on my behalf then. Trust me it never goes over well when I ask for donations. :)

**Comment by slavap** [comment]
@madame-rachelle sounds scary :-)

**Comment by madame-rachelle** [comment]
You're the one saying it will be no problem to get one. :) My life is not significantly worse having a lack of a feature I can't use, anyway, and have very little interest in, to begin with. It's also not as easy as copy-pasting code from one source port to another like you seem to think it is - if it was, having the card would not even be necessary. But if there's one thing I learned over the years - it's how many times I got burned putting in a commit without testing it first. And with something this significant, I sure as shit am not going to do something like that. To be quite frank I think you are critically overestimating the "ease" of putting a feature like this in when it comes from an incompatible source port. Sure, it will be "easier" than writing it from scratch but that doesn't mean it's just "E-Z-P-Z". If it is so easy - go ahead and do it yourself. :) Pull requests are accepted here.

**Comment by slavap** [comment]
@madame-rachelle First I have to refresh my C++ skills, the last time I've touched it was 25 years ago :-) Next, I have to figure out how 3D renderer works (had some experience, but again ages ago). Sounds like semi-impossible task to me :-)
