### ISSUE TITLE
[BUG] I can't open a door in gzdoom 

### ISSUE THREAD

**Issue by NTechV** [coelckers/gzdoom#1592]
### GZDoom version

gzdoom 4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I cannot open a door in gzdoom by using any control, so I stay stuck in the first level.
I also can't control "switches" which now always stay in their default setting.

My config: https://gist.github.com/NTechV/bd2dfe43ab1065c8c58d7d07b75f4396

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Find any door in gzdoom 4.7.1
2. Try to open it 
3. Can't open

**Comment by coelckers** [comment]
How did you try to open the door? According to your config it is bound to the 'E' key.

**Comment by NTechV** [comment]
Thanks, I didn't notice that, but you solved my problem so now I can open the doors in gzdoom.

**Comment by steviator** [comment]
WTF? why does it default to something so idiotic? Do you hate your users or something?

**Comment by madame-rachelle** [comment]
That's what modern games default to. And it's what is default when you pick the modern keybinding style.

If we hated our users you wouldn't be able to change your keybindings at all. You wouldn't be able to change preferences. Hell you might not even be able to download GZDoom. You're making a mountain out of an ant hill.
