### ISSUE TITLE
[BUG] GZDoom fails to build with Alpine Linux Edge

### ISSUE THREAD

**Issue by antonialoytorrens** [coelckers/gzdoom#1595]
### GZDoom version

4.7.1

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Alpine Linux (musl-based distribution)

### Relevant hardware info

x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GZDoom fails to build with Alpine Linux (the edge version) (at the time of writing, after 3.15 release).

There's a high possibility that this failing issue occurs due to the migration to GCC-11, as Alpine Linux 3.15 version was released with GCC-10 and it compiles and runs fine.

---

Additional notes: Building with git (last checked: ~2 days ago) also makes no difference at all.

### Steps to reproduce the behaviour.

1. Decompress sources.
2. Compile the package with Alpine Linux Edge (any architecture, try with x86_64 for example).

This is the configuration used to compile GZDoom:
```
	cmake -B build \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_SHARED_LIBS=True \
		-DDYN_GTK=OFF \
		-DDYN_OPENAL=OFF \
		$CMAKE_CROSSOPTS .
	cmake --build build
```

3. See the compiling errors.

### Your configuration

```ini
Not relevant.
```

### Provide a Log

See [this log](https://gist.githubusercontent.com/antonialoytorrens/b324b8a02f2b2e24c7fd53fd92f666e8/raw/023e1bab8cc60fbdc186c50cff89eb72e28f78e7/GZDoom_Alpine_Linux_Edge_GCC11.txt) for details.

---

If you want to see a working example to compare, you can [click here](https://gist.githubusercontent.com/antonialoytorrens/8e4b69932b9e705c25a95477d6577d20/raw/8e0249875b210259de2b88358cd0c6db6a7c806b/GZDoom_Alpine_Linux_3.15_Build.txt) for GZDoom 3.15 Build with GCC10.

**Comment by coelckers** [comment]
It fails on this:

CMake Error at src/CMakeLists.txt:359 (message):
  C++ compiler doesn't support thread_local storage duration specifier

Which makes me question that compiler's validity. In any case, this is something we cannot fix.

**Comment by antonialoytorrens** [comment]
Thank you!

**Comment by nekopsykose** [comment]
i would say this is more of a cmake issue, e.g. https://stackoverflow.com/questions/35457533/findpkgconfig-with-set-target-properties-is-unusable-for-setting-cflags-ldflags  

it can be fixed with a `string(REPLACE ";" " " MUSL_FTS_LDFLAGS "${MUSL_FTS_LDFLAGS}")` after the pkg_check_modules invocation

**Comment by nekopsykose** [comment]
are you still interested in fixing this? i can open a patch with the above added line if you want me to- this path is only hit in the musl-fts using case, so it's only broken there.  

there is also a requirement to add -lfts to tools/zipdir since the fts_ functions are used in it.
