### ISSUE TITLE
[BUG] Crash when starting gzdoom under vulkan

### ISSUE THREAD

**Issue by x3003** [coelckers/gzdoom#1607]
### GZDoom version

gzdoom-x64-g4.8pre-399-g2be13e1b9

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Relevant hardware info

AMD r5, GTX 1060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When starting a game on gzdoom x64 399 it crashes. gzdoom x64 396 is ok, no crash.
It crashes w/ vulkan, but not w/ opengl.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start gzdoom
2. Select game, like freedoom
3. Crash

### Provide a Log

[CrashReport130522.zip](https://github.com/coelckers/gzdoom/files/8687230/CrashReport130522.zip)

**Comment by x3003** [comment]
Starting a game now works w/ pre 405, but loading a map (for example freedoom) crashes gzdoom under vulkan. No problem w/ opengl. 

[CrashReport150522.zip](https://github.com/coelckers/gzdoom/files/8695004/CrashReport150522.zip)

**Comment by OrdinaryMagician** [comment]
I think this can be closed as fixed, now.

**Comment by x3003** [comment]
Yes, it's fixed. Thanks for that.
