### ISSUE TITLE
[Feature] Rain in sectors

### ISSUE THREAD

**Issue by GeordanKrahn** [coelckers/gzdoom#1614]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

AMD Ryzen 7 3700X, Nvidia RTX 3700, 16GB ram

### Is your feature request related to a problem? Please describe.

No. I am a modder creating a mod and would like to see a new feature.

### Describe the solution you'd like

I would like to see the possibility of adding rain effects to specific sectors.

### Describe alternatives you've considered

I have considered using ZScipt to create a screen effect, however i do not know how to make this apply to specific sectors.

**Comment by coelckers** [comment]
This is clearly in DIY territory and should be done with ACS in your mod.
