### ISSUE TITLE
[BUG] SDL2 version check fails against latest upstream

### ISSUE THREAD

**Issue by sjnewbury** [coelckers/gzdoom#1617]
### GZDoom version

Since git e4ada10e78f6083ba97b81a5bec0ff3b1ef429cf

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Gentoo / custom

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Upstream SDL2 has switched versioning scheme whereby patchlevel(micro)->minor so the check fails as now patch == 0

Simple fix would be to explicitly check for the full version as below:

```
--- ./src/common/platform/posix/sdl/sdlglvideo.cpp~	2021-10-20 07:18:37.000000000 +0100
+++ ./src/common/platform/posix/sdl/sdlglvideo.cpp	2022-05-28 20:53:49.223014740 +0100
@@ -398,7 +398,7 @@
 	// Fail gracefully if we somehow reach here after linking against a SDL2 library older than 2.0.6.
 	SDL_version sdlver;
 	SDL_GetVersion(&sdlver);
-	if (!(sdlver.patch >= 6))
+	if (sdlver.major == 2 && sdlver.minor == 0 && !(sdlver.patch >= 6))
 	{
 		I_FatalError("Only SDL 2.0.6 or later is supported.");
 	}


```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Link against upstream SDL2
2. Run gzdoom

**Comment by coelckers** [comment]
That would fail just as badly if the version gets bumped to 2.1.0.

**Comment by mjr4077au** [comment]
The fix here would be `if (!SDL_VERSION_ATLEAST(2, 0, 6))`. Source: https://wiki.libsdl.org/SDL_VERSION_ATLEAST

**Comment by sjnewbury** [comment]
> The fix here would be `if (!SDL_VERSION_ATLEAST(2, 0, 6))`. Source: https://wiki.libsdl.org/SDL_VERSION_ATLEAST.
> 
> If the two variables above the if statement are not further used within the function, they can also be removed as they won't be necessary anymore.

Which was used in src/CMakeLists.txt in the same commit!

**Comment by mjr4077au** [comment]
> Which was used in src/CMakeLists.txt in the same commit!

It should have been used in both spots. If you send a PR through, I'm sure it'd get merged. I'd remove `SDL_version sdlver;` and `SDL_GetVersion(&sdlver);` as well at the same time.

**Comment by Gaerzi** [comment]
Copy-paste error? I don't see how https://github.com/coelckers/gzdoom/commit/7eb12fa9fb5950ae221b5f6b89bc6f6019322493 relates to an SDL issue.
