### ISSUE TITLE
Random crash during saving

### ISSUE THREAD

**Issue by alexey-lysiuk** [coelckers/gzdoom#162]
I've got random crash during saving while playing [Tungsten](https://www.doomworld.com/idgames/levels/doom2/Ports/s-u/tungsten) map with 605a60d1d68840edd63c52d9d8c1cf3cb7664167.
```
PStruct::WriteFields(ar=0x00007fff5fbfcc58, addr=0x0000000104366600, fields=0x000000013493eb28) + 104 at dobjtype.cpp:2320
RecurseWriteFields(type=0x000000013493ea80, ar=0x00007fff5fbfcc58, addr=0x0000000104366600) + 299 at dobjtype.cpp:2715
PClass::WriteAllFields(this=0x000000013493ea80, ar=0x00007fff5fbfcc58, addr=0x0000000104366600) const + 37 at dobjtype.cpp:2737
DObject::SerializeUserVars(this=0x0000000104366600, arc=0x00007fff5fbfcc58) + 79 at dobject.cpp:516
FSerializer::WriteObjects(this=0x00007fff5fbfcc58) + 256 at serializer.cpp:969
FSerializer::GetCompressedOutput(this=0x00007fff5fbfcc58) + 130 at serializer.cpp:1105
G_SnapshotLevel() + 183 at g_level.cpp:1528
G_DoSaveGame(okForQuicksave=true, filename=(Chars = "save0.zds"), description="1") + 378 at g_game.cpp:2258
G_Ticker() + 461 at g_game.cpp:1080
TryRunTics() + 1147 at d_net.cpp:1946
```
One _probably_ important thing: processed class was `None`, i.e. its name has zero index. Is correct behavior to store such object in saved game?

It happened just once and I cannot reproduce it anymore. I loaded [this save](https://github.com/coelckers/gzdoom/files/677087/save0.zds.zip) (it's just `save0.zds` with `.zip` extension added to pass GitHub filter), run to mancubus and saved there. 

It was on macOS so I grabbed a core dump in order to get any needed information later. Please let me know what else I can check.

**Comment by coelckers** [comment]
That sounds odd, but if it cannot be reproduced I can't fix it. I do not even have an idea what kind of object caused the crash.

**Comment by coelckers** [comment]
Pointless to keep open.
