### ISSUE TITLE
[BUG] Sound in Background option not working

### ISSUE THREAD

**Issue by Some1NamedNate** [coelckers/gzdoom#1631]
### GZDoom version

GZDoom 4.8.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home 21H2

### Relevant hardware info

Intel Core i7-10700KF, Nvidia GeForce RTX 2080 SUPER

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Sound in Background option, when set to "On," is supposed to play BGM when the GZDoom window is inactive. Here the BGM stops playing when I Alt+Tab away from the window, open the Start menu via the Windows key, etc.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to Options -> Sound Options -> Advanced options; make sure "Sound in Background" is set to "On."
2. Press the Windows/Super key. Or Alt+Tab away from the GZDoom window
3.

### Your configuration

```ini
https://gist.github.com/Some1NamedNate/cd731791736f577054daa054aa6c1757
```

**Comment by madame-rachelle** [comment]
`i_soundinbackground` was a misnomer for the other thing it did - forcefully pause the game. Since there's so much confusion coming from this I am going to forcefully set `i_pauseinbackground` to false in the next version - as a one-time-only thing.

**Comment by madame-rachelle** [comment]
Actually I will set it to `!(i_soundinbackground)` instead.
