### ISSUE TITLE
[BUG] script error starting boa

### ISSUE THREAD

**Issue by x3003** [coelckers/gzdoom#1636]
### GZDoom version

gzdoom-x64-g4.9pre-10-g34f1b23c3

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Relevant hardware info

amd r5, gtx 1060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When starting blade of agony (git), you'll get a script error w/ g4.9pre-10-g34f1b23c3.
Maybe it was already in pre9, but that archive is bad.
Last working version was 4.9 pre 4.

![Script_error](https://user-images.githubusercontent.com/77861029/173672267-6f00facc-485f-44e1-a70e-b1cee4f11935.jpg)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start boa git
2. Wait
3. Error shows up

**Comment by SanyaWaffles** [comment]
looks like this is going to be fixed soon

https://github.com/coelckers/gzdoom/pull/1635

**Comment by x3003** [comment]
Thx for fixing.
