### ISSUE TITLE
Gargoyles suffer pain when hitting each other

### ISSUE THREAD

**Issue by Blue-Shadow** [coelckers/gzdoom#164]
**Tested with: 2.3pre-1092-g605a60d**

When gargoyles slam into each other, the slammed gargoyle suffers pain from the event (pain only, no damage), something they didn't do before.

Note that I'm talking about pain here, not infighting, which was an issue that was fixed recently.

**Comment by coelckers** [comment]
Are you sure about that? I just analyzed the original P_DamageMobj from Heretic and cannot find anything in there that would prevent setting the pain state if called with zero damage.

**Comment by Blue-Shadow** [comment]
So, the current behavior of suffering pain is an original Heretic behavior? If that's the case, then this can be closed.

**Comment by alexey-lysiuk** [comment]
Sorry but this is not original behavior.

I checked in DOS Heretic 1.3 and Chocolate Heretic and there was no `IMPPAI` sound during gargoyles collisions.
Using a000b572049da4b085d3ec5087af8a3c04b15abe I hear this sound pretty clearly. Compatibility settings have no influence on this.

**Comment by Gaerzi** [comment]
Then let's unclose this.

**Comment by alexey-lysiuk** [comment]
Played a bit with Choco in debugger. `P_DamageMobj()` is called but returns right from [here](https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/src/heretic/p_inter.c#L1245). It's definitely 
> Shouldn't happen

**Comment by Gaerzi** [comment]
Interesting. That does abort the function before [the skullfly check](https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/src/heretic/p_map.c#L351-L360) happens, and therefore prevents the collision from doing any damage. Doesn't this mean that gargoyles also cannot hurt disciples?

**Comment by coelckers** [comment]
They have damage 0, so they never hurt anything. Wow, what a pile of garbage...

**Comment by coelckers** [comment]
Original behavior has been restored. Which makes the flag essentially broken again. But considering its overall lack of usefulness that shouldn't matter.
