### ISSUE TITLE
Feature Request: Adding Support in GZDoom for Doom 64?

### ISSUE THREAD

**Issue by MasterO2** [coelckers/gzdoom#1646]
@madame-rachelle @coelckers 

On 23rd June 2022, GOG launched its own release for Doom 64:

https://www.gog.com/en/game/doom_64

Can this be supported by GZDoom?  Please advise.  

If that is **not** possible, I will close this thread accordingly.

Also, thank you both and all of the contributors to GZDoom for continuing to make this source port great.

**Comment by coelckers** [comment]
No, we cannot support this unless there is an official source code release under a permissive license.
GZDoom is being used as a commercial engine which means it cannot incorporate any code that is even remotely dubious.

**Comment by thekovic** [comment]
Doom 64 EX source code is released under GNU GPL. It's not as accurate as the official port but the differences are small so you could totally use that as a base to get DOOM64.wad playing.

**Comment by madame-rachelle** [comment]
And to that I say - it's been out and available for so long that if GZDoom ever was going to do that, it probably would've done it by now. Not saying it's impossible - just saying don't count your chickens just now.

**Comment by madame-rachelle** [comment]
To be clear I would love Doom64 support in GZDoom as well - but it's not as simple as you guys seem to be desperate to think that it is. It's not just a simple YOOOINK OH HERE'S SUDDEN DOOM 64 SUPPORT OUT OF NOWHERE BECAUSE OF A SOURCE CODE I FOUND. If you really think it's that simple go ahead and do it yourself - let me know how that goes. Meanwhile the rest of us have IRL, family, work, health, and a whole bunch of other things we have to deal with as well.

**Comment by MajorCooke** [comment]
Blzut3 was doing something with this a long time ago but he stopped working on it for an unknown reason, just thought I'd chime in with that.

**Comment by thekovic** [comment]
The least that can be done is un-close this issue because clearly Doom 64 support is a feature that is _possible_ to be added. Believe me, I understand that actually implementing it is not going to be quick and easy but I'm frankly getting tired of Doom 64 constantly being shoved away to a corner and nobody caring about it.

**Comment by MajorCooke** [comment]
The reason he closed it was because he's not going to do it. You'll have to find someone else to do it.

**Comment by MajorCooke** [comment]
> No, we cannot support this unless there is an official source code release under a permissive license. GZDoom is being used as a commercial engine which means it cannot incorporate any code that is even remotely dubious.

That means it's an absolute no. So, no, there's no point to reopening this.

**Comment by TheKins** [comment]
> GZDoom is being used as a commercial engine which means it cannot incorporate any code that is even remotely dubious.

So when's the Strife support getting removed? Need to know in advance so I can adjust/replace all the Strife-isms in my project (dialogue system etc.)

**Comment by Edward850** [comment]
> > No, we cannot support this unless there is an official source code release under a permissive license. GZDoom is being used as a commercial engine which means it cannot incorporate any code that is even remotely dubious.
> 
> That means it's an absolute no. So, on the contrary, there's no point to reopening this. Lets say that it is compatible, it seems to me that no one wants to do it. If that were the case, then it's been closed because it's not a priority or something they don't want to implement themselves.

Strife lives under the exact same circumstances. Doom64Ex is fully usable as a reverse engineering base if you also accept Strife's same legal status of its work too.

**Comment by madame-rachelle** [comment]
Whatabout-ism and "proving someone else wrong" just to show off your internet cajones and how super-duper smart you are (wow congrats, really deserves a medal, that one) is not getting you any closer to getting this implemented. Take that insanity somewhere else, not here.

**Comment by coelckers** [comment]
> So when's the Strife support getting removed?

Never. Last time I checked the complete source for Strife VE is being shipped as part of the game, licensed under the GPLv3. That's a very different situation than Doom 64.
