### ISSUE TITLE
[BUG] Plasma balls crash the game instantly.

### ISSUE THREAD

**Issue by GeminiCrafterMan** [coelckers/gzdoom#1655]
### GZDoom version

g4.9pre-85-ga4aca9bd9-m

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

EndeavourOS (Previously Manjaro, still happened there)

### Relevant hardware info

AMD Ryzen 5 5600G (Previously 3 3200G, still happened there)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Only happens when using the default decals, and ONLY when shooting the Plasma Rifle at a wall. PlasmaBall1 and PlasmaBall2 don't do it, despite using the same effect. Happens in Doom 1, Doom 2, and FreeDoom, as well as maybe other games, but I haven't tested those. If I rebuild the game and change that specific decal, it works fine.

https://user-images.githubusercontent.com/8532523/177224390-7fb1d7d6-d4e8-4458-a4cc-636536951b8e.mp4

### Steps to reproduce the behaviour.

1. Obtain a Plasma Rifle
2. Shoot it at a wall. Things, floors, etc. are not affected.
3. There is no step 3, the game crashes then and there.

### Your configuration

```ini
https://gist.github.com/GeminiCrafterMan/4d088c6c084fd2918e9480ed76687fd4
```

### Provide a Log

*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x1c

System: Linux dustin-pc 5.18.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 29 Jun 2022 23:03:08 +0000 x86_64 GNU/Linux

GZDoom version g4.9pre-85-ga4aca9bd9-m (a4aca9bd9c4d8d8c75596173071af86e8fa43e03)
Command line: /usr/bin/gzdoom
Wad 0: gzdoom.pk3
Wad 1: game_support.pk3
Wad 2: doom_complete.pk3
Wad 3: 150skins.wad
Wad 4: adultcarewithgun.wad
Wad 5: DoomGremlinGuy.wad
Wad 6: FreeDoomGuy.wad
Wad 7: mario-mpa.wad
Wad 8: Slayer.wad
Wad 9: zombiemanskin.wad
Wad 10: brightmaps.pk3
Wad 11: lights.pk3
Wad 12: cblood.pk3

Current map: test

viewx = -3050.610348
viewy = 338.195805
viewz = 41.000000
viewangle = -88.346558

Executing: gdb --quiet --batch --command=gdb-respfile-9obSNW

**Comment by coelckers** [comment]
Please try to narrow it down to one of those countless add-ons you load.
Does not happen for me on Windows with nothing loaded but the base game
