### ISSUE TITLE
[BUG] IVF Videos Unable to Open

### ISSUE THREAD

**Issue by sk33z3r** [coelckers/gzdoom#1656]
### GZDoom version

4.8.1

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

NixOS 22.05

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The wiki doesn't go into much detail about video formats or how to convert to them, and seems to indicate that IVF video + OGG audio is the main method for playing back Intro videos for a map or episode.

I used this command to convert a WebM video to IVF
```
ffmpeg -i Endeavor.webm -vcodec copy -an -f ivf LAUNCH.ivf
```

The resulting IVF file loads and playsback in VLC with no issue, however when I attempt to add the video using the `Intro` property for my map, I get the following error in console:

```
LAUNCH: Unable to open video
```

I'm wondering if there's a special way that the video needs to be converted. I tried to use ffmpeg to create `.smk` and `.mve`, but both failed with the version I have saying the output format wasn't suitable; I haven't been able to test any other video format.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Get a WebM for your Intro and confirm it plays back
2. Convert WebM to separate IVF and OGG files
3. Confirm audio and video play back
4. Import IVF and OGG files to WAD
5. Add Intro section to ZMAPINFO under `GameInfo`, `Cluster`, `Episode`, or `Map`
```
Intro
{
    Video = "LAUNCH"
}
```
6. Load your WAD in GZDoom and start a new game

Expected:
Video file plays back and finds the matching LAUNCH.ogg file for audio

Actual:
Error in console: `LAUNCH: Unable to open video`

**EDIT**:

I re-read the wiki, and it does mention that the `Video` property needs to point to the file, including extension. However, I tried this and got the same result.

```
Intro
{
    Video = "LAUNCH.ivf"
}
```

**EDIT2**:

I also tried specifying the audio file in a couple ways, but to no avail.

```
Intro
{
    Video = "LAUNCH.ivf"
    Sound = "LAUNCH"
}
```

and

```
Intro
{
    Video = "LAUNCH.ivf"
    Sound = "video"
}
```

where my SNDINFO has this for the ogg file

```
video LAUNCH
```

**Comment by alexey-lysiuk** [comment]
We cannot debug textual description of some problem. Please post a sample that showcases the issue.

**Comment by sk33z3r** [comment]
I'm pretty sure there's something up with how I'm transcoding, so I guess I'm also looking for answers to these questions to determine if this is even a bug or not.

* Are there any restraints on filesize or video length?
* Any restraints on video dimensions?
* Are there special filters (e.g., FPS, color, etc.) that should be applied when transcoding?
* Can I get an example of a video that _does_ work to compare?

**Comment by alexey-lysiuk** [comment]
We need a complete sample that can be run via `-file` command line switch, not just some parts of it.
Help us help you. Nobody is interested in spending time replicating your mod.

**Comment by Talon1024** [comment]
I tested this by putting the movies into a small mod with this MAPINFO, and it works just fine for me:

    gameinfo {
        Intro { Video = "movies/test.ivf" }
    }

**Comment by OrdinaryMagician** [comment]
Works fine on my end. Do keep in mind the video path is absolute. Unless you put the videos in the root of your archive, you'll need to specify what directory they're in.

**Comment by sk33z3r** [comment]
@OrdinaryMagician 
> Edit: Wait, you did it in a WAD. I'm pretty sure that simply won't work, you need either an archive or a folder.

You seem to have hit on something that I didn't know. Thanks for actually reading through the report and pointing this out. There are no notes regarding this on the Wiki, could you point me to where it might give more info? (besides [this page](https://zdoom.org/wiki/Using_ZIPs_as_WAD_replacement))

My video plays back as long as I open a directory or ipk3.

**Comment by Blue-Shadow** [comment]
While the wiki doesn't explicitly mention that you need a PK3/ZIP, [it does mention](https://zdoom.org/wiki/Cutscene_MAPINFO_properties) that you need to specify the path to the file (and gave an example, even).

**Comment by sk33z3r** [comment]
> While the wiki doesn't explicitly mention that you need a PK3/ZIP, [it does mention](https://zdoom.org/wiki/Cutscene_MAPINFO_properties) that you need to specify the path to the file (and gave an example, even).

Indeed, and I even mentioned that I tried that in an edit to the main ticket.

**Comment by Gaerzi** [comment]
The thing is that "LAUNCH.ivf" is not a valid lump name in a WAD file. For a start, it has 10 characters. So was your video even in your archive at all?

**Comment by sk33z3r** [comment]
> The thing is that "LAUNCH.ivf" is not a valid lump name in a WAD file. For a start, it has 10 characters. So was your video even in your archive at all?

It was imported to the WAD file, as mentioned in the bug report steps. One thing I didn't note, I had it at the top level. I tried it the following ways:

With Filename: `LAUNCH`
* Video: `LAUNCH`
* Video: `/LAUNCH`

With Filename: `LAUNCH.ivf`
* Video: `LAUNCH`
* Video: `LAUNCH.ivf`
* Video: `/LAUNCH.ivf`

In the identical setup, no changes to filenames whatsoever, only changing to ipk3 format instead WAD, is what resolved the issue. My placement, syntax, transcoding was all correct.
