### ISSUE TITLE
[BUG] double/float comparison not working

### ISSUE THREAD

**Issue by Talon1024** [coelckers/gzdoom#1658]
### GZDoom version

GZDoom g4.8.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel Core i3-3110M CPU, Intel HD Graphics 4000 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When doubles are compared to floats, the result is incorrect.

This has caused an issue in Wolfenstein: Blade of Agony where the player's disguise item makes them unable to move through doors or gates while crouching. I did a [quick workaround](https://github.com/Realm667/WolfenDoom/commit/fb59220e3c879bdf10b80e3ad72381b3c87a2d3c), but that doesn't solve the issue.

The comparison works properly on GZDoom 4.7.1 because it converts the scale to doubles, but it does not work properly on GZDoom 4.8.1.

Here's a small [mod](https://github.com/coelckers/gzdoom/files/9056937/doublefloatcompare.zip) demonstrating the issue.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch GZDoom with the test mod provided above, and start a new game.
2. Enter `give ScaleCompareTest` into the console.
3. If it works properly, you should see "Owner's scale is NOT 0.650." only once.

### Provide a Log

GZDoom 4.7.1 (correct):
    
    MAP01 - Entryway
    
    ]give scalecomparetest
    Owner's scale is NOT 0.650.
    ]give scalecomparetest
    Owner's scale is already 0.650. Doing nothing
    ]give scalecomparetest
    Owner's scale is already 0.650. Doing nothing

GZDoom 4.8.1 (incorrect):

    MAP01 - Entryway
    
    ]give scalecomparetest
    Owner's scale is NOT 0.650.
    ]give scalecomparetest
    Owner's scale is NOT 0.650.
    ]give scalecomparetest
    Owner's scale is NOT 0.650.
    ]give scalecomparetest
    Owner's scale is NOT 0.650.

**Comment by Blue-Shadow** [comment]
I believe this is already fixed in 4.8.2. So try that.

**Comment by Talon1024** [comment]
No dice, float/double comparisons don't work properly in 4.8.2 either.

**Comment by MrRaveYard** [comment]
I think this a float vs double precision issue.

float:
0.64999997615814208984375000000000000000000000000000000
double:
0.65000000000000002220446049250313080847263336181640625

(values are from a custom test program)

**Comment by Talon1024** [comment]
Was scale changed internally from double to float between GZDoom 4.7.1 and 4.8.0?

**Comment by MrRaveYard** [comment]
Yes https://github.com/coelckers/gzdoom/commit/f9bf6f931129f1614b3837e09c77773815c1e911

**Comment by OrdinaryMagician** [comment]
Does it work if `~==` is used instead of just `==`?

**Comment by MrRaveYard** [comment]
> Does it work if `~==` is used instead of just `==`?

Nope

**Comment by coelckers** [comment]
Looks like the scale vector needs to be reverted to double. Well, here goes the chance of saving some space in AActor... :(

**Comment by SanyaWaffles** [comment]
That's a shame, but it seems this unfortunately breaks stuff too much with no obvious workaround.

**Comment by Talon1024** [comment]
> Looks like the scale vector needs to be reverted to double. Well, here goes the chance of saving some space in AActor... :(

Why not convert/coerce both values to float if either value being compared is a float?

**Comment by coelckers** [comment]
Currently there are no float opcodes whatsoever, this would require a lot of support code.
I'm sorry, but as I see it, single precision floats in ZScript are not viable for anything that requires precise comparisons.

**Comment by coelckers** [comment]
fixed in aae1d1439abc12b926b97f28fc7a4707c95564ee

**Comment by SanyaWaffles** [comment]
Still a few floats in actor.zs causing zscript compilation to fail.
