### ISSUE TITLE
problem / "lag"

### ISSUE THREAD

**Issue by ammonita** [coelckers/gzdoom#166]
More about it here ( with example wad ):
http://zandronum.com/tracker/view.php?id=2967

Shooting a monster that drops random blood causes a *lag* for a ~0.3 sec.
It only happens at start of each map. Few shots and effect goes away.

**Comment by alexey-lysiuk** [comment]
The lag depends greatly on particular hardware/OS/drivers combination.
For example, I'm experiencing delays like 100 ms using integrated Intel on macOS. And Apple's drivers are far from being the best.

At least 25 textures need to be processed and uploaded to video memory with every new blood variation which was not spawned yet on this map.
By the way do you have texture upscaling enabled? This option may increase processing times greatly.
Texture precaching (`gl_precache` CVAR) may also affect the delay as it's disabled by default. 

There is no global textures precache list. For custom maps there is `PrecacheTextures` property in `MAPINFO` although I have no idea is it applicable to your mod.

**Comment by coelckers** [comment]
About this: "Attempt to get invalid state Death from actor RBloodHitP10."

Your death state is just a 'stop', meaning the state is effectively not present. All the subclasses try to jump here but cannot find a valid death state. Either add a valid state after the 'death' label or change the 'goto death' to 'stop'.

**Comment by coelckers** [comment]
Fixing this will require global Precache... entries in the gameinfo section in MAPINFO so that they get set for each map. On my system without scaling there is no lag. Even with 4x upscaling it's only very minor.

**Comment by ammonita** [comment]
This seems not to work for me but I am not sure this is how PrecacheTextures is used.
adddefaultmap { 

 PrecacheTextures = "1P10A0", "1P10B0", "1P10C0", "1P10D0", "1P10E0", "1P10F0", 
                                 "1P10G0", "1P10H0", "1P10I0", "1P10J0", "1P10K0", "1P10L0", 
			         "1P10M0" (...)

}

**Comment by coelckers** [comment]
The usage is correct but this won't be added to the previously defined maps.
This will need an engine side fix where you can specify textures to be precached globally.

**Comment by ammonita** [comment]
Ok. Thank you for the support.

**Comment by coelckers** [comment]
Moved to Mantis tracker with a more specific title.
