### ISSUE TITLE
[BUG]  lzdoom does not start after updating llvm-libs (13.0.1-6 → 14.0.6-1)

### ISSUE THREAD

**Issue by Vomitor456** [coelckers/gzdoom#1667]
### GZDoom version

lzdoom 2.88-b2

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Please describe your specific OS version

manjaro arm xfce for pinebook pro

### Relevant hardware info

Pinebook Pro, RK3399, 4 GB Ram, Mali T 860Mp4Gpu, Panfrost Driver

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hy! I am on Manjaro ARM unstable branch and this update today: llvm-libs (13.0.1-6 → 14.0.6-1)

let lzdoom from Aur dont start.

i recompile the aur package but it does not work.

the only thing i can do is to downgrade to llvm-libs 13.0.1-6 
with 14.0.6-1 it will not start

Here my terminal output:

[patrick@patrick ~]$ lzdoom %F
LZDoom <unknown version> -  - SDL version
Compiled on Jul  4 2022

LZDoom version <unknown version>
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /usr/share/lzdoom/lzdoom.pk3, 713 lumps
 adding /usr/share/lzdoom/game_support.pk3, 291 lumps
 adding /home/patrick/.config/lzdoom/DOOM2.WAD, 2919 lumps
I_Init: Setting up machine state.
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device Internes Audio Headphones + Speaker
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 481.75 ms
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading custom status bar definition.
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
Using video driver x11
OpenGL load failed. No OpenGL acceleration will be used.

*** Fatal Error ***
!!! Failed to exec debug process

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by alexey-lysiuk** [comment]
LZDoom is [here](https://github.com/drfrag666/gzdoom).
