### ISSUE TITLE
A case of crash upon picking up an item

### ISSUE THREAD

**Issue by Blue-Shadow** [coelckers/gzdoom#172]
**Tested with: 2.3.0 (64-bit)**

With the supplied test file, start a new Doom 2 game. From the console, summon `NCItem`. Save the game, then load the savegame. Pickup the item, and GZDoom will crash.

https://www.dropbox.com/s/diopnud0csdabq8/pickup_crash_demo.zip?dl=1 (includes both the test file and crash report)

**Comment by coelckers** [comment]
fixed
