### ISSUE TITLE
Sprites (or player models) appear when traversing floor/ceiling portals

### ISSUE THREAD

**Issue by AFADoomer** [coelckers/gzdoom#173]
[Commit a000b57](https://github.com/coelckers/gzdoom/commit/a000b572049da4b085d3ec5087af8a3c04b15abe) looks like it fixed the sprite/model appearing through wall portals, but ceiling/floor portals still have some issues  (though they are far less evident that before).  The portal/bridge thing [test map that I made for an unrelated bug](http://afadoomer.com/files/PortalBridge.wad) still shows the problem when you cross certain planes while walking up/down the stairs.

**Comment by coelckers** [comment]
I cannot reproduce it. It was this map after all that prompted me to fix it because it was really bad on it.
What do I need to do to see the glitch?

**Comment by AFADoomer** [comment]
Stand on one of the upper steps (either 3d floor or thing-based) so that the player actor is crossing the portal plane, then turn in place.  It looks like it only happens when the player has no velocity (x, y, or z).

**Comment by coelckers** [comment]
fixed
