### ISSUE TITLE
ZScript #defines and/or macros

### ISSUE THREAD

**Issue by MajorCooke** [coelckers/gzdoom#174]
Would it be possible to potentially create macros and/or defines for the sake of shortening longer bits of code? 

Example in global space:
`#define HorizVel cos(pitch)*20;`
`#define VertVel -sin(pitch)*20;`

Then later in the states:
`TNT1 A 0 A_SpawnItemEx("Rocket",0,0,0,HorizVel,0,VertVel,0,SXF_NOCHECKPOSITION|SXF_SETTARGET);`

**Comment by coelckers** [comment]
#defines like in C probably won't happen. Writing a preprocessor is far from trivial. There may be other enhancements later but they are not on my roadmap.
