### ISSUE TITLE
Crash very early during multiplayer

### ISSUE THREAD

**Issue by LionsPhil** [coelckers/gzdoom#176]
GZDoom 2.3.0. The attached [CrashReport.zip](https://github.com/coelckers/gzdoom/files/681575/CrashReport.zip) is while using a pretty hefty mod (Guncaster), but we were able to reproduce the problem with vanilla Ultimate DOOM, and also with DOOM 2.

To reproduce:
1. Start 2 player internet co-op game
2. One player should run for the armour to the left of spawn, up the stairs on E1M1
3. As they cross the doorway, their game will lock up and/or crashdump

Up until that point multiplayer appears to be functioning normally, i.e. we can see each-other move.

Does not seem to affect it:
- If the pk3 in this report is loaded
- If it's the host or the client
- Timing, much...you seem to have to move for it to happen (although when we tried DOOM 2 it did seem to crash while we were firing from the starting ledge of the first mission). Making a beeline for the armour or dancing around the starting area for a moment first makes no difference: you crash as you pass the doorway.

Cannot reproduce in singleplayer.

**Comment by MajorCooke** [comment]
Multiplayer is unfortunately very broken. I don't think it'll be fixed anytime soon either.

**Comment by coelckers** [comment]
Sadly, there is currently nobody who understands the mechanics of multiplayer well enough to fix this.

**Comment by MajorCooke** [comment]
Re-opened?

**Comment by coelckers** [comment]
I accidentally closed it. The issue needs investigation even if it may have to be done by someone else.

**Comment by LionsPhil** [comment]
Dang. Take it it's been broken for a while? (i.e. going back a few versions won't help, and for fixing it it's way more involved than bisecting recent changes)

**Comment by coelckers** [comment]
This most likely broke during the implementation of portals and the floating point conversion earlier this year.
The code that's suspected to be responsible is player prediction which is doing some really ugly things to ensure that it doesn't alter the game state. The guy who wrote this stuff is currently not available to fix it.

**Comment by coelckers** [comment]
Looks like it's fixed now after realizing what was the likely issue.

**Comment by edward-san** [comment]
Which commit addresses the issue?

**Comment by alexey-lysiuk** [comment]
Most likely it's from [this branch](https://github.com/coelckers/gzdoom/tree/PredictionStuff). I guess Graf didn't pushed it to `master`yet.

**Comment by Toybasher** [comment]
I can report the same when running hideous destructor. Happens with the then-latest (I don't know if newer builds were released) dev build on January 6th, and 2.3.0 stable.

We can move fine, but the SECOND we make negative movement across a linedef, the guy who crossed freezes. Once he disconnects, the game continues, and if I cross that same linedef I also freeze and crash. 

I can walk up a ledge fine, but not down ledges. Jumping is fine, too. I have not tested if jumping off a ledge causes a crash, though.

**Comment by alexey-lysiuk** [comment]
It's fixed in the latest devbuild only ([win32](https://devbuilds.drdteam.org/gzdoom/gzdoom-g2.4pre-42-g62ea83a.7z)/[win64](https://devbuilds.drdteam.org/gzdoom/gzdoom-x64-g2.4pre-42-g62ea83a.7z)).
