### ISSUE TITLE
Yellow Screen trying to play vanilla doom 2

### ISSUE THREAD

**Issue by doonoo** [coelckers/gzdoom#177]
I can hear stuff, but when I try to go to the menu I see nothing.
[see image](http://imgur.com/FbLA0Ak)

**Comment by coelckers** [comment]
I need more info about your system What graphics card? What Windows version?
Please start GZDoom with 'gzdoom +logfile log.txt' and post that file here.

**Comment by doonoo** [comment]
Radeon HD 3650, Windows 7
[log.txt](https://github.com/coelckers/gzdoom/files/683269/log.txt)

**Comment by coelckers** [comment]
I see this is a rather old first generation card with GL 3.x support. Unfortunately some drivers for those have bugs when running an OpenGL core profile.

I only can give a few recommendations here:

1. Make sure you have the latest driver installed. ATI's drivers for OpenGL 3.x have been suffering from countless bugs over time and many revisions are just broken.

2. If that doesn't help, can you try running GZDoom with '-glversion 2', which reverts the engine to a setting that doesn't use a core profile? That will disable a few features but it may help with the driver.

**Comment by doonoo** [comment]
Turns out I just needed to update my drivers, thanks.

**Comment by coelckers** [comment]
Good to hear.
