### ISSUE TITLE
PowerDamage is broken

### ISSUE THREAD

**Issue by Talon1024** [coelckers/gzdoom#178]
If the player has a powerup based on PowerDamage, and he tries to attack an enemy, the game will crash.

Example PK3: [damagepowerup.zip](https://github.com/coelckers/gzdoom/files/682110/damagepowerup.zip). I've replaced the chainsaw with a double damage powerup pickup via mapinfo.

**Comment by Talon1024** [comment]
BTW, PowerDamage works in ZDoom, but not GZDoom for some reason.

**Comment by coelckers** [comment]
This was caused by converting them to scripts which triggered a bug in the code generator.

**Comment by Blue-Shadow** [comment]
Does this also fix PowerProtection? I noticed that it doesn't absorb damage while having it.
