### ISSUE TITLE
Sounds being overrided despite SNDINFO limit settings. 

### ISSUE THREAD

**Issue by ammonita** [coelckers/gzdoom#180]
Note discussion in the link was a bit chaotic the most important thing is my second last post (Filystea).
The test file is here http://zandronum.com/tracker/view.php?id=2971 

Generally I had this problem before with chaingunner but managed to fix it changing sound mp3/ogg to wav format. I just assumed that the wav format is better and did not try to explain it more.

But recently I saw that if I try to use with limit 0 soldier to shoot few times more than usually the sound gets overrided. the thing is it uses the wav format for sound and yet the problem occurs.

I also checked as someone else in the pointed topic that this happens on gzdoom. In test file just go to zombieguy with God mod on (it shoots back massively) and hit it. it will shoot back and the sound will get overrided. Or you won't even heard it.

**Comment by coelckers** [comment]
This sounds like each sound gets cut off by the next - which is precisely what happens if you play two sounds on the same channel.
