### ISSUE TITLE
"State *****.* not flagged for use in weapons"

### ISSUE THREAD

**Issue by Seeesq** [coelckers/gzdoom#181]
Allo, I've recieved this bug with 2 WADs now: Twilight Warrior and Zan Zan (gzdoom version of course), and whenever trying to fire a weapon it will pop up with "State *****.* not flagged for use in weapons" (In the case of the fists weapon in Zan Zan, it was state Bluetorch.0). I've had this issue in the official 2.3 release and the newest git build (2.4 pre-16).

**Comment by coelckers** [comment]
fixed
