### ISSUE TITLE
Bug with function A_SetSize()

### ISSUE THREAD

**Issue by GitAlekv** [coelckers/gzdoom#183]
The radius varies good. But the problem with the height.
The video shows how the height is changed.
Testing in gzdoom-g2.4pre-16-g96623b3.7z	Jan 03 2017 03:34:34

https://youtu.be/AO62amzQCDU

**Comment by coelckers** [comment]
If I understand this correctly, this is a PlayerPawn, right? In that case it's not possible to change height, because it will restore it each tick based on the crouch factor.

**Comment by GitAlekv** [comment]
Yes, the player is based on PlayerPawn.
Very bad .. Tell me is it possible to add to in function A_SetSize  (..., bool ingnore CrouchFactor)?
Unfortunately, the standard Crouch factor is not very convenient to modify the player crouching.
arg like "bool ingnore CrouchFactor" very usefull for create custom Crouch state.

**Comment by coelckers** [comment]
It's not that easy. Allowing this will require some deeper changes in the player logic.

**Comment by GitAlekv** [comment]
Thanks for the answer.
I only hope that in the future it will be possible to dynamically change the height of the player in the State.

**Comment by MajorCooke** [comment]
Ooof. This bug is being painful to me as well. I think getting this fixed would make things a lot easier rather than dealing with 2 morphs as once.

**Comment by coelckers** [comment]
Don't expect any quick solutions. This one involves some heavy refactoring of player logic.

**Comment by jewalky** [comment]
I circumvent this by simply setting height every tic, and this is probably that exact bug that causes the problem that I've mentioned in ZScript discussion thread, with AttackZOffset constantly going back to it's old value. So that one doesn't need investigation now.

**Comment by MajorCooke** [comment]
It actually still does, because that's more processing time still being added. Remember, it has to reset the blockmap. And that's the very thing that was causing NOINTERACTION to lag.

**Comment by GitAlekv** [comment]
"simply setting height every tic"

A_SetSize, do not change the height of the player's hitbox! Even if you write A_SetSize everywhere in every tick.
This script shows the change in the height of the player, but in fact its height does not change! 
script "test" ENTER {
while (TRUE) {
PrintBold(s:"height   ",d:GetActorProperty(0,APROP_Height),s:"\nRadius   ",d:GetActorProperty(0,APROP_Radius),s:"\n\nheightF   ",f:GetActorProperty(0,APROP_Height),s:"\nRadiusF   ",f:GetActorProperty(0,APROP_Radius));
		Delay(1);}
}

To check, download the MAP test:
https://goo.gl/4c3gRh
and try to pass under a ceiling or a custom invisible bridge (Z height of the bridge = 10 and the ceiling height = 10). When a player is walking, his the height = 5

**Comment by MajorCooke** [comment]
...Of course it does that when you use ACS. ACS lags behind, but not zscript.

**Comment by coelckers** [comment]
Moved to Mantis tracker.
