### ISSUE TITLE
Problems with friendlies and +COUNTKILL

### ISSUE THREAD

**Issue by MajorCooke** [coelckers/gzdoom#185]
Friendly actors with +COUNTKILL will count up the monsters killed upon death, but they never update how many total monsters there are that are killable.

I'm trying to make it so friendly monsters really do add to both the monsters left and monsters killed. Monsters left, however, is never updated.

I can't tell if this is an issue that can be fixed internally or if a new flag is needed, +COUNTKILLFRIENDLY to work with this.

**Comment by coelckers** [comment]
Friendly monsters never count unless you start some flag hacking. They are not supposed to count and the CountsAsKill() function excludes friendlies unconditionally.

**Comment by coelckers** [comment]
Ok then. There's no bug here and without any response to my comment it's pointless to keep this open.

**Comment by MajorCooke** [comment]
I thought you were going to close it from the very beginning so I didn't say anything.
