### ISSUE TITLE
Particle automatic fade is not smooth

### ISSUE THREAD

**Issue by Accensus** [coelckers/gzdoom#188]
By 'not smooth' I mean that if I have a particle with a lifetime of 175 (5 seconds), it does fade out slowly, but alpha does not go down fast enough. In other words, when the lifetime has reached 0, the alpha is still ~0.5. The longer the lifetime, the easier it is to see notice the issue.

EDIT: In fact, the particle does not last longer than 5 seconds it seems, no matter what I put for lifetime.

**Comment by coelckers** [comment]
I can't say without more information, like the code you use. The particle timing math is not the most precise, though - some combinations just do not work right due to roundoff errors.

**Comment by Accensus** [comment]
```C++
Actor L50Beacon : BulletPuff
{
   var int user_i;
   var int user_n;

   VSpeed 0

   +PUFFONACTORS
   +BLOODLESSIMPACT
   -BLOODSPLATTER

   States
      {
      Spawn:
         TNT1 A 35 NODELAY
         {
            user_n = 88;
            for(user_i = 1; user_i <= 360; user_i++)
            {
               A_SpawnParticle("Green", SPF_RELATIVE | SPF_FULLBRIGHT, 210, 16, user_i, 512, 0, -28);
            }
         }
      RainDownHell: 
         TNT1 A 2
         {
            if(user_n)
            {
               A_SpawnItemEx("L50Fireball", random(0, 512), 0, ceilingz - 32, 0, 0, -32, random(1, 360));
               A_SpawnItemEx("L50Fireball", random(0, 512), 0, ceilingz - 32, 0, 0, -32, random(1, 360));
               user_n--;
            }
            return A_JumpIf(!user_n, "Null");
         }
         Loop
      Crash:
         Stop
      Melee:
         Stop
      }
}
```
This is it, pretty much. Lifetime just doesn't go above ~175 tics. It looks as if it's capped. I believe that might be a separate issue, as it's like that regardless of _fadestepf_.

**Comment by coelckers** [comment]
The math in the particle code was particularly shoddy, using bytes for both translucency and lifetime which just caused some precision issues with your precise values. Changing those to floats fixed the problem.

It was just the totally wrong way to save some memory.

**Comment by MajorCooke** [comment]
Just pointing out that you had changed this in the maint branch but not master.
