### ISSUE TITLE
Not sure this is bug but reporting. A_SpawnItemEx seems to not wok in few situations

### ISSUE THREAD

**Issue by ammonita** [coelckers/gzdoom#192]
Problem in general is that A_SpawnItemEx does not spawn in some  situations monster actors

test file is here: http://zandronum.com/tracker/view.php?id=2973

Description is:

It does not matter where the monster actor is defined. It won't spawn.

summon zom1 or zom4 they can't summon it self or monster defined somewhere.

But if you define monster with monster spawner it will be spawned (example zom3),

And if you give flag to monster THRUACTORS and take it away at spawn. It will be spawned. (zom2)

----------------------------

**Comment by coelckers** [comment]
See my reply at the Zandronum report.
