### ISSUE TITLE
$DOOMWADDIR ignored

### ISSUE THREAD

**Issue by rnkn** [coelckers/gzdoom#193]
In both my `.bashrc` and `.bash_profile` I've set:
~~~
export DOOMWADDIR="${HOME}/Library/Application Support/DOOM"
~~~
but upon launching I still get "Cannot find game IWAD" error.

If I rename the above folder to GZDoom or symlink it everything works fine.

Should I be setting `$DOOMWADDIR` elsewhere?

**Comment by alexey-lysiuk** [comment]
I assume that you are describing the version for macOS.

The question is how do you start GZDoom?
If you are running it from Terminal, please post the command line because it works for me.
If you are running from Finder or other GUI app, it works as intended because none of those apps use your Bash profile.

**Comment by rnkn** [comment]
From Finder. Yep that makes sense, thanks.

**Comment by Gaerzi** [comment]
From a cursory glance it doesn't seem possible to set environment variables for the Finder, since most people instead recommend to replace your app with a shell script that exports the env. variables directly (or source your bash profile) and then run the app.

**Comment by alexey-lysiuk** [comment]
It's possible but quite complicated, see [this discussion](http://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite) for example.
Apple's guys are thinking that only geeks need this feature :suspect:

**Comment by DUOLabs333** [comment]
I've been having a similar problem (also on macOS) --- environment variables like `VK_LOADER_DEBUG`, `VK_LAYER_PATH`, and `VK_LOADER_LAYERS_ENABLE`, are not picked up by gzdoom, regardless of whether I run `open -a GZDoom.app`, or `./GZDoom.app/Contents/MacOS/gzdoom` directly (both inside the terminal).
