### ISSUE TITLE
Can't link git or 2.3.0 on GNU/Linux

### ISSUE THREAD

**Issue by Q3CPMA** [coelckers/gzdoom#194]
Hello,

when trying to build either from git or the 2.3.0 tarball, I get this error when linking.
```
cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DDYN_FLUIDSYNTH=OFF
make -j8
...
CMakeFiles/zdoom.dir/tempfiles.cpp.o: In function `FTempFileName::FTempFileName(char const*)':
tempfiles.cpp:(.text+0x7): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/zdoom.dir/i_module.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/lib64/libdl.so.2: error adding symbols: DSO missing from command line
```

**Comment by alexey-lysiuk** [comment]
What's the distro? What's the output of `gcc --version`?

**Comment by Q3CPMA** [comment]
gcc 4.9.4 on Gentoo
`gcc (Gentoo 4.9.4 p1.0, pie-0.6.4) 4.9.4`

**Comment by alexey-lysiuk** [comment]
Could you please try with configure with `cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DDYN_FLUIDSYNTH=OFF CMAKE_EXE_LINKER_FLAGS="-ldl"` command line?

**Comment by Q3CPMA** [comment]
```
cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DDYN_FLUIDSYNTH=OFF CMAKE_EXE_LINKER_FLAGS="-ldl"
CMake Error: The source directory "/home/user/bin/gzdoom-g2.3.0/CMAKE_EXE_LINKER_FLAGS=-ldl" does not exist.
Specify --help for usage, or press the help button on the CMake GUI
```
tried passing it before, like this
```
CMAKE_EXE_LINKER_FLAGS="-ldl" cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DDYN_FLUIDSYNTH=OFF
```
but the error didn't go away.

**Comment by alexey-lysiuk** [comment]
My bad, it should be
`cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DDYN_FLUIDSYNTH=OFF -DCMAKE_EXE_LINKER_FLAGS="-ldl"`

**Comment by Q3CPMA** [comment]
Yep, it works now.

**Comment by alexey-lysiuk** [comment]
Of course this should to be handled automatically in CMake files.
Although I'm not a Linux expert, need someone more experienced to do it right.

@Blzut3, could you please take a look?

**Comment by Q3CPMA** [comment]
It's probably worse saying that 2.2.0 didn't have this problem (on the same machine).

**Comment by alexey-lysiuk** [comment]
Related changes were made after 2.2.0 was released.

**Comment by edward-san** [comment]
Is DYN_FLUIDSYNTH option enabled? If not, can you rebuild with that option on?

**Comment by Q3CPMA** [comment]
Sorry, I don't want to install Fluidsynth.
