### ISSUE TITLE
GZDoom const error

### ISSUE THREAD

**Issue by MajorCooke** [coelckers/gzdoom#195]
[This one](https://github.com/coelckers/gzdoom/commit/82adc5bf1e3864e21d8a1b0abb43655dffa6d9bd) did it.

Script error, "gzdoom.pk3:zscript/base.txt" line 253:
Unexpected 'const'
Expecting '.' or 'class' or identifier or 'color' or 'int8' or 'uint8' or 'int16' or 'uint16' or 'int' or 'uint' or 'bool' or 'float' or 'double' or 'string' or 'vector2' or 'vector3' or 'name' or 'sound' or 'state' or 'let' or 'readonly' or 'map' or 'array' or 'in' or 'out' or 'optional'

Execution could not continue.

1 errors while parsing gzdoom.pk3:zscript/chex/chexplayer.txt

**Comment by raa-eruanna** [comment]
Got this issue too, when I was updating QZDoom.

**Comment by coelckers** [comment]
Will be fixed with the next commit. Can't do right now because I am doing some larger change.
