### ISSUE TITLE
TryMove bugginess

### ISSUE THREAD

**Issue by MajorCooke** [coelckers/gzdoom#196]
Until recently, TryMove was behaving fine. Not anymore.

Load up [D4D.pk3](https://drive.google.com/file/d/0B6VLnV8LvStuVGMyZkFVLU9qcG8/view?usp=sharing) with Going Down, proceed to map07: Bad Reception. The elevator door will open and there's a mancubus at the desk, just below the stairs.

He'll shuffle around a little bit and become stuck on the edge of the desk.

[This is the code used for the AI.](https://github.com/MajorCooke/Doom4Doom/blob/master/ZD4D/Monsters/MonsterBase.txt#L127)

[This is how he calls the code.](https://github.com/MajorCooke/Doom4Doom/blob/master/ZD4D/Monsters/Fatso.txt#L613)

**Comment by coelckers** [comment]
What is "recently"?

**Comment by MajorCooke** [comment]
I don't really know. I only started noticing it today but you did make some changes to the position checking, so I'm wondering if that had anything to do with it.

**Comment by MajorCooke** [comment]
...Nevermind, I forgot to set NOINTERACTION on the spawners...
