### ISSUE TITLE
A_FaceTarget delay?

### ISSUE THREAD

**Issue by Accensus** [coelckers/gzdoom#197]
If the player is moving fast enough, calling both A_FaceTarget and A_CustomRailgun in the same tic still makes the railgun fire behind the player. If you circle an enemy fast enough, it may not be able to hit you at all with a railgun.

**Comment by coelckers** [comment]
This is a fully intentional piece of coding inside A_CustomRailgun which adds a bit of inaccuracy to the aiming if the target is moving fast. Otherwise the railgun would become an unfair monster weapon.

**Comment by Accensus** [comment]
Well, guess I'll have to find a different way to make lightning effects that shoot down BFG balls. I tried to use it so that whenever a BFGBall came inside the perimeter of a given monster, a railgun with high _maxdiff_ fires at it and destroys it. Only works if the projectile is fired directly at the monster and not to its left or right. I wonder how I can implement that using different means...

**Comment by coelckers** [comment]
Maybe that inaccuracy bit should be made configurable.

**Comment by Accensus** [comment]
Seems like a good idea. I'd love to see it in someday, because it'll enable some simple solutions to a problem which would otherwise need to be hacked around.  I'd rather avoid hacks.
