### ISSUE TITLE
Messages don't display

### ISSUE THREAD

**Issue by Gothic-HP** [coelckers/gzdoom#198]
Messages don't appear on screen when you have the option on.

**Comment by alexey-lysiuk** [comment]
Could you please be more specific? What's the missing message and what's the exact name of the option?

**Comment by Gothic-HP** [comment]
I meant log messages, like pickup messages, obituaries, chat, etc.

**Comment by alexey-lysiuk** [comment]
There are several options that affect those messages.
What are the values of `msg`, `show_messages` and `con_notifylines` CVARs?

**Comment by alexey-lysiuk** [comment]
So why did you set `con_notifylines` to zero? This effectively disables all messages.
Set it to four (the default value) or to any appropriate value above zero.

**Comment by Gothic-HP** [comment]
Except they were default, I didn't set anything. Anyways, thanks for fixing my problem.
