### ISSUE TITLE
Crash on exit in Debian: d2a51a57e1

### ISSUE THREAD

**Issue by MatthewTheGlutton** [coelckers/gzdoom#199]
Using:
Debian Jessie
http://members.shaw.ca/vaecrius/hd/hd20170102.zip
gzdoom -file hd.pk7 -nomusic +map map01 -noautoload

If I jump, taunt or shoot before exiting, it's fine. (EDIT: if all I do is lightly tap a direction or crouch key, or deploy a DERP or switch weapons before exiting, it doesn't seem to count as having done anything and the crash/hang still happens. EDIT2: even if I wait until the DERP has killed the two zombies at the Map01 start before quitting, I still get the crash. Seems like something has to be done to the playerpawn?)

If I immediately exit once I enter the map, though, GZDoom will do one of the following, in descending order of frequency:

1. crash with a segmentation fault
2. crash with a crash popup window and crash log [gzdoom-crash.log.txt](https://github.com/coelckers/gzdoom/files/691918/gzdoom-crash.log.txt)
3. crash, then hang on the message "Fatal Error", then overwrite gzdoom.ini with a blank file

This does not happen with 2.3.0 but I don't know when it started happening.
EDIT: Nor does it happen in 2.3.1.

**Comment by alexey-lysiuk** [comment]
Are you building GZDoom by yourself? Is the any custom build options used or is it just `cmake && make`?

**Comment by MatthewTheGlutton** [comment]
cmake -DCMAKE_BUILD_TYPE=Release ..;make -j 4

**Comment by MatthewTheGlutton** [comment]
There's an enter script that gives PowerFrightener at the very start of the map. Shooting, sprinting and taunting all take it away, but crouching and using items or switching weapons do not.

If I do nothing else but go into the console and type "take powerfrightener" and quit, there is no crash.

Going into Map01 without any mods loaded and typing "give powerfrightener" and quitting also results in a crash.

**Comment by alexey-lysiuk** [comment]
Does it crash in `Debug` or `RelWithDebInfo` configuration?

**Comment by MatthewTheGlutton** [comment]
No crash with Debug.

Crash with RelWithDebInfo.

**Comment by edward-san** [comment]
Can you attach the crash log you get with the RelWithDebInfo build?

**Comment by MatthewTheGlutton** [comment]
[gzdoom-crash.log.zip](https://github.com/coelckers/gzdoom/files/692459/gzdoom-crash.log.zip)

commands:
gzdoom -noautoload -warp 01
give powerfrightener;wait 1;quit

**Comment by edward-san** [comment]
@coelckers the crash log shows that the VM code tried to get a NULL frame. Is that really alright to allow the VM to run when the program quits?

**Comment by coelckers** [comment]
I can't see how this happens. The level shutdown occurs before the shutdown of the class system so normally at that point all data should still be present. Of course I cannot rule out that some things are done in a bad order here, but this is using ZDoom's own mechanism for running exit handlers to ensure proper order.

Actually, the VM cannot run anymore after the object system has been taken down, that's why at the moment the Destroy method cannot be overridden.

**Comment by alexey-lysiuk** [comment]
For me the crash is in different place, inside `glibc` to be precise:
```
#0  _int_malloc (av=0x7ffff5788620 <main_arena>, bytes=512) at malloc.c:3540
#1  0x00007ffff545f020 in __GI___libc_malloc (bytes=512) at malloc.c:2891
#2  0x00000000007915fe in M_Malloc (size=size@entry=512) at src/m_alloc.cpp:65
#3  0x0000000000753398 in TArray (max=64, this=<synthetic pointer>) at src/tarray.h:140
#4  PClass::StaticShutdown () at src/dobjtype.cpp:2960
#5  0x000000000054ca92 in call_terms () at src/posix/sdl/i_main.cpp:126
#6  0x00007ffff541ab29 in __run_exit_handlers (status=0, listp=0x7ffff57885a8 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#7  0x00007ffff541ab75 in __GI_exit (status=<optimized out>) at exit.c:104
#8  0x00000000007180f3 in Cmd_quit (argv=..., who=<optimized out>, key=<optimized out>) at src/c_cmds.cpp:103
#9  0x0000000000723459 in C_DoCommand (cmd=<optimized out>, keynum=0) at src/c_dispatch.cpp:627
#10 0x000000000072378e in AddCommandString (cmd=0x3943e10 "\234\371\245\002", keynum=0)
    at src/c_dispatch.cpp:728
#11 0x00000000007238df in DWaitingCommand::Tick (this=0x3775650) at src/c_dispatch.cpp:223
#12 0x000000000075d515 in DThinker::CallTick (this=this@entry=0x3775650) at src/dthinker.cpp:561
#13 0x000000000075d60c in DThinker::TickThinkers (list=list@entry=0x1f7dea0 <DThinker::Thinkers+800>, dest=dest@entry=0x0)
    at src/dthinker.cpp:527
#14 0x000000000075d6de in DThinker::RunThinkers () at src/dthinker.cpp:474
#15 0x0000000000857bc4 in P_Ticker () at src/p_tick.cpp:130
#16 0x000000000076d1ef in G_Ticker () at src/g_game.cpp:1207
#17 0x000000000073e574 in TryRunTics () at src/d_net.cpp:1947
#18 0x00000000007377e5 in D_DoomLoop () at src/d_main.cpp:1017
#19 0x0000000000739ea7 in D_DoomMain () at src/d_main.cpp:2678
```
Looks like there is a memory corruption in optimized build.

`RelWithDebInfo` is exiting just fine on macOS but the issue is present indeed on Debian (using GCC 4.9.2 at least) where this backtrace was obtained.

`Linux jessie64 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux`

**Comment by coelckers** [comment]
The entire engine shutdown mechanism is one huge clusterfuck of bad implementation, largely inherited from Boom. Normally it should ensure everything is cleaned up BEFORE calling exit and not solely depending on atexit.

This will definitely not be easy to sort out.

**Comment by coelckers** [comment]
For the record: This had been refactored in the mean time
