### ISSUE TITLE
Particle fading bug

### ISSUE THREAD

**Issue by MajorCooke** [coelckers/gzdoom#200]
`A_SpawnParticle(444444,SPF_RELATIVE,35,random(4,12),random(-45,45),frandom(0.0,2.0),0,frandom(-1.0,1.0),frandom(0.1,1.0),0,frandom(-1.0,1.0),frandom(0.0,0.02),frandom(-0.04,0.04),-0.1,frandom(0.3,0.6))`

Colors invert over half the fade time.

**Comment by MajorCooke** [comment]
In fact, it not only inverts, it also backward-renders everything behind it. Reminds me of the bloom bug a while ago where noclipping through a wall could cause a colorized flash. If many particles are stacked together it can even make a square around it sometimes.

**Comment by coelckers** [comment]
I saw some inversion but only the very last frames. Changed it so that if the alpha goes below 0, the particle gets deleted. That check was previously hidden in an implicit overflow.
