### ISSUE TITLE
Enemies seeing players; static portals

### ISSUE THREAD

**Issue by Enjay001** [coelckers/gzdoom#201]
When using static portals, enemies can see the player (and consequently wake up and try to attack) if the portal effectively moves the two areas over each other even if there should be no way for the enemies to see the player (e.g. the floor that the player standing on is higher than the ceiling of the room with the enemies).

The attached ZIP/PK3 contains 2 identical maps with the exception that MAP01 uses an interactive portal and MAP02 uses a static one.

If you load the attached zip and start MAP01, there is quiet. If you go through the door to the front left of you, across the room beyond to the door at the far side and then down the stairs about half way down you cross a portal line and are transported to a different section. At the bottom of the stairs there is a room full of imps.
If you warp to MAP02 the setup is the same but the imps in the lower room wake up as soon as the level starts and start throwing fireballs at you which, obviously, can't actually reach you.

[ImpPortal.zip](https://github.com/coelckers/gzdoom/files/692131/ImpPortal.zip)

**Comment by coelckers** [comment]
fixed
