### ISSUE TITLE
Heresiarch isn't calling its death script

### ISSUE THREAD

**Issue by FishyClockwork** [coelckers/gzdoom#202]
...Because the 'override' keyword is missing: https://github.com/coelckers/gzdoom/blob/master/wadsrc/static/zscript/hexen/heresiarch.txt#L115

**Comment by coelckers** [comment]
Damnit. That should have triggered a compile error.

**Comment by coelckers** [comment]
Shit. 7 places where 'override' was missing. It will now properly report these as an error but it seems I can do a 2.3.2 very soon. :(
