### ISSUE TITLE
[Software] BOOM Transfer Sky Texture, Tall Sky Bug

### ISSUE THREAD

**Issue by Hellser** [coelckers/gzdoom#204]
Cross posting from ZDoom Forums: https://forum.zdoom.org/viewtopic.php?f=2&t=52271

I'm creating a map for BOOM and due to the nature of how we got the maps set up, we have to use "Transfer Sky Texture to Tagged Sectors" action (271 and 272). I dislike how ZDoom was handling the stretched sky so I 'borrowed' the sky textures from Skulltag to make a quick sky replacement for Doom. Was looking good until I looked all the way up.

If this is something that the QZDoom team can instead of fixing it in the base Source Port, I'll send this issue over to them.

[Test Map](https://dl.dropboxusercontent.com/u/52515188/zdoomtallskyboomissue.pk3)
[What happens](http://i.imgur.com/2UCNWEs.png)
[What it's suppose to look like](http://i.imgur.com/TCp6MpV.png)

**Comment by coelckers** [comment]
Is this only in the software renderer or also in the hardware renderer?

**Comment by Hellser** [comment]
Only software. The OpenGL renderer doesn't have this issue.
