### ISSUE TITLE
SNDINFO and MAPINFO cannot take additional portions after name

### ISSUE THREAD

**Issue by MatthewTheGlutton** [coelckers/gzdoom#207]
You can have a decorate.1.txt and a decorate.2.txt in a mod and both will load. Same thing with textures.

It used to be that you could have a mapinfo.3.txt or a sndinfo.4.txt in similar fashion, but now it seems they will be ignored unless they are named mapinfo.txt and sndinfo.txt.

Is this an oversight when making some other change? Or was this set like this to prevent some other thing?

**Comment by coelckers** [comment]
This was a bug in older versions which didn't properly truncate a lump name. Only the last extension may be truncated, but with DECORATE already being 8 characters long anything above will also be truncated. MAPINFO is only 7 characters so the first '.' will remain.

This behavior is needed to allow lump names containing '.'s.
